// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: shorturls/generator/service/v1/service.proto

package servicev1

import (
	_ "github.com/FreibergVlad/url-shortener/proto/pkg/permissions/messages/v1"
	v1 "github.com/FreibergVlad/url-shortener/proto/pkg/shorturls/generator/messages/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_shorturls_generator_service_v1_service_proto protoreflect.FileDescriptor

const file_shorturls_generator_service_v1_service_proto_rawDesc = "" +
	"\n" +
	",shorturls/generator/service/v1/service.proto\x12\x1eshorturls.generator.service.v1\x1a\x1cgoogle/api/annotations.proto\x1a)permissions/messages/v1/permissions.proto\x1a>shorturls/generator/messages/v1/create_short_url_request.proto\x1a?shorturls/generator/messages/v1/create_short_url_response.proto2\xed\x01\n" +
	"\x18ShortURLGeneratorService\x12\xd0\x01\n" +
	"\x0eCreateShortURL\x126.shorturls.generator.messages.v1.CreateShortURLRequest\x1a7.shorturls.generator.messages.v1.CreateShortURLResponse\"M\x92\xb5\x18\x10short-url:create\x82\xd3\xe4\x93\x023:\x01*\"./v1/organizations/{organization_id}/short-urlsB\xa9\x02\n" +
	"\"com.shorturls.generator.service.v1B\fServiceProtoP\x01ZXgithub.com/FreibergVlad/url-shortener/proto/pkg/shorturls/generator/service/v1;servicev1\xa2\x02\x03SGS\xaa\x02\x1eShorturls.Generator.Service.V1\xca\x02\x1fShorturls\\Generator_\\Service\\V1\xe2\x02+Shorturls\\Generator_\\Service\\V1\\GPBMetadata\xea\x02!Shorturls::Generator::Service::V1b\x06proto3"

var file_shorturls_generator_service_v1_service_proto_goTypes = []any{
	(*v1.CreateShortURLRequest)(nil),  // 0: shorturls.generator.messages.v1.CreateShortURLRequest
	(*v1.CreateShortURLResponse)(nil), // 1: shorturls.generator.messages.v1.CreateShortURLResponse
}
var file_shorturls_generator_service_v1_service_proto_depIdxs = []int32{
	0, // 0: shorturls.generator.service.v1.ShortURLGeneratorService.CreateShortURL:input_type -> shorturls.generator.messages.v1.CreateShortURLRequest
	1, // 1: shorturls.generator.service.v1.ShortURLGeneratorService.CreateShortURL:output_type -> shorturls.generator.messages.v1.CreateShortURLResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shorturls_generator_service_v1_service_proto_init() }
func file_shorturls_generator_service_v1_service_proto_init() {
	if File_shorturls_generator_service_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shorturls_generator_service_v1_service_proto_rawDesc), len(file_shorturls_generator_service_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shorturls_generator_service_v1_service_proto_goTypes,
		DependencyIndexes: file_shorturls_generator_service_v1_service_proto_depIdxs,
	}.Build()
	File_shorturls_generator_service_v1_service_proto = out.File
	file_shorturls_generator_service_v1_service_proto_goTypes = nil
	file_shorturls_generator_service_v1_service_proto_depIdxs = nil
}
