// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: shorturls/generator/service/v1/service.proto

package servicev1

import (
	context "context"
	v1 "github.com/FreibergVlad/url-shortener/proto/pkg/shorturls/generator/messages/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShortURLGeneratorService_CreateShortURL_FullMethodName = "/shorturls.generator.service.v1.ShortURLGeneratorService/CreateShortURL"
)

// ShortURLGeneratorServiceClient is the client API for ShortURLGeneratorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShortURLGeneratorServiceClient interface {
	CreateShortURL(ctx context.Context, in *v1.CreateShortURLRequest, opts ...grpc.CallOption) (*v1.CreateShortURLResponse, error)
}

type shortURLGeneratorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShortURLGeneratorServiceClient(cc grpc.ClientConnInterface) ShortURLGeneratorServiceClient {
	return &shortURLGeneratorServiceClient{cc}
}

func (c *shortURLGeneratorServiceClient) CreateShortURL(ctx context.Context, in *v1.CreateShortURLRequest, opts ...grpc.CallOption) (*v1.CreateShortURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.CreateShortURLResponse)
	err := c.cc.Invoke(ctx, ShortURLGeneratorService_CreateShortURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShortURLGeneratorServiceServer is the server API for ShortURLGeneratorService service.
// All implementations must embed UnimplementedShortURLGeneratorServiceServer
// for forward compatibility.
type ShortURLGeneratorServiceServer interface {
	CreateShortURL(context.Context, *v1.CreateShortURLRequest) (*v1.CreateShortURLResponse, error)
	mustEmbedUnimplementedShortURLGeneratorServiceServer()
}

// UnimplementedShortURLGeneratorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShortURLGeneratorServiceServer struct{}

func (UnimplementedShortURLGeneratorServiceServer) CreateShortURL(context.Context, *v1.CreateShortURLRequest) (*v1.CreateShortURLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateShortURL not implemented")
}
func (UnimplementedShortURLGeneratorServiceServer) mustEmbedUnimplementedShortURLGeneratorServiceServer() {
}
func (UnimplementedShortURLGeneratorServiceServer) testEmbeddedByValue() {}

// UnsafeShortURLGeneratorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShortURLGeneratorServiceServer will
// result in compilation errors.
type UnsafeShortURLGeneratorServiceServer interface {
	mustEmbedUnimplementedShortURLGeneratorServiceServer()
}

func RegisterShortURLGeneratorServiceServer(s grpc.ServiceRegistrar, srv ShortURLGeneratorServiceServer) {
	// If the following call pancis, it indicates UnimplementedShortURLGeneratorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShortURLGeneratorService_ServiceDesc, srv)
}

func _ShortURLGeneratorService_CreateShortURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.CreateShortURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortURLGeneratorServiceServer).CreateShortURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShortURLGeneratorService_CreateShortURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortURLGeneratorServiceServer).CreateShortURL(ctx, req.(*v1.CreateShortURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShortURLGeneratorService_ServiceDesc is the grpc.ServiceDesc for ShortURLGeneratorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShortURLGeneratorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shorturls.generator.service.v1.ShortURLGeneratorService",
	HandlerType: (*ShortURLGeneratorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateShortURL",
			Handler:    _ShortURLGeneratorService_CreateShortURL_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shorturls/generator/service/v1/service.proto",
}
