// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: invitations/service/v1/service.proto

package servicev1

import (
	v1 "github.com/FreibergVlad/url-shortener/proto/pkg/invitations/messages/v1"
	_ "github.com/FreibergVlad/url-shortener/proto/pkg/permissions/messages/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_invitations_service_v1_service_proto protoreflect.FileDescriptor

const file_invitations_service_v1_service_proto_rawDesc = "" +
	"\n" +
	"$invitations/service/v1/service.proto\x12\x16invitations.service.v1\x1a\x1cgoogle/api/annotations.proto\x1a7invitations/messages/v1/accept_invitation_request.proto\x1a8invitations/messages/v1/accept_invitation_response.proto\x1a7invitations/messages/v1/create_invitation_request.proto\x1a8invitations/messages/v1/create_invitation_response.proto\x1a)permissions/messages/v1/permissions.proto2\x8e\x03\n" +
	"\x11InvitationService\x12\xd1\x01\n" +
	"\x10CreateInvitation\x120.invitations.messages.v1.CreateInvitationRequest\x1a1.invitations.messages.v1.CreateInvitationResponse\"X\x92\xb5\x18\x1eorganization-invitation:create\x82\xd3\xe4\x93\x020:\x01*\"+/v1/organizations/{organization_id}/invites\x12\xa4\x01\n" +
	"\x10AcceptInvitation\x120.invitations.messages.v1.AcceptInvitationRequest\x1a1.invitations.messages.v1.AcceptInvitationResponse\"+\x82\xd3\xe4\x93\x02%:\x01*\" /v1/organizations/invites/acceptB\xf6\x01\n" +
	"\x1acom.invitations.service.v1B\fServiceProtoP\x01ZPgithub.com/FreibergVlad/url-shortener/proto/pkg/invitations/service/v1;servicev1\xa2\x02\x03ISX\xaa\x02\x16Invitations.Service.V1\xca\x02\x16Invitations\\Service\\V1\xe2\x02\"Invitations\\Service\\V1\\GPBMetadata\xea\x02\x18Invitations::Service::V1b\x06proto3"

var file_invitations_service_v1_service_proto_goTypes = []any{
	(*v1.CreateInvitationRequest)(nil),  // 0: invitations.messages.v1.CreateInvitationRequest
	(*v1.AcceptInvitationRequest)(nil),  // 1: invitations.messages.v1.AcceptInvitationRequest
	(*v1.CreateInvitationResponse)(nil), // 2: invitations.messages.v1.CreateInvitationResponse
	(*v1.AcceptInvitationResponse)(nil), // 3: invitations.messages.v1.AcceptInvitationResponse
}
var file_invitations_service_v1_service_proto_depIdxs = []int32{
	0, // 0: invitations.service.v1.InvitationService.CreateInvitation:input_type -> invitations.messages.v1.CreateInvitationRequest
	1, // 1: invitations.service.v1.InvitationService.AcceptInvitation:input_type -> invitations.messages.v1.AcceptInvitationRequest
	2, // 2: invitations.service.v1.InvitationService.CreateInvitation:output_type -> invitations.messages.v1.CreateInvitationResponse
	3, // 3: invitations.service.v1.InvitationService.AcceptInvitation:output_type -> invitations.messages.v1.AcceptInvitationResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_invitations_service_v1_service_proto_init() }
func file_invitations_service_v1_service_proto_init() {
	if File_invitations_service_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_invitations_service_v1_service_proto_rawDesc), len(file_invitations_service_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_invitations_service_v1_service_proto_goTypes,
		DependencyIndexes: file_invitations_service_v1_service_proto_depIdxs,
	}.Build()
	File_invitations_service_v1_service_proto = out.File
	file_invitations_service_v1_service_proto_goTypes = nil
	file_invitations_service_v1_service_proto_depIdxs = nil
}
