// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: shorturls/management/service/v1/service.proto

package servicev1

import (
	_ "github.com/FreibergVlad/url-shortener/proto/pkg/permissions/messages/v1"
	v1 "github.com/FreibergVlad/url-shortener/proto/pkg/shorturls/management/messages/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_shorturls_management_service_v1_service_proto protoreflect.FileDescriptor

const file_shorturls_management_service_v1_service_proto_rawDesc = "" +
	"\n" +
	"-shorturls/management/service/v1/service.proto\x12\x1fshorturls.management.service.v1\x1a\x1cgoogle/api/annotations.proto\x1a)permissions/messages/v1/permissions.proto\x1aIshorturls/management/messages/v1/delete_short_url_by_org_id_request.proto\x1aJshorturls/management/messages/v1/delete_short_url_by_org_id_response.proto\x1aFshorturls/management/messages/v1/get_short_url_by_org_id_request.proto\x1aGshorturls/management/messages/v1/get_short_url_by_org_id_response.proto\x1a<shorturls/management/messages/v1/get_short_url_request.proto\x1a=shorturls/management/messages/v1/get_short_url_response.proto\x1aGshorturls/management/messages/v1/list_short_url_by_org_id_request.proto\x1aHshorturls/management/messages/v1/list_short_url_by_org_id_response.proto\x1aIshorturls/management/messages/v1/update_short_url_by_org_id_request.proto\x1aJshorturls/management/messages/v1/update_short_url_by_org_id_response.proto2\xd1\t\n" +
	"\x19ShortURLManagementService\x12\x80\x01\n" +
	"\vGetShortURL\x124.shorturls.management.messages.v1.GetShortURLRequest\x1a5.shorturls.management.messages.v1.GetShortURLResponse\"\x04\x8a\xb5\x18\x00\x12\x85\x02\n" +
	"\x1bGetShortURLByOrganizationID\x12D.shorturls.management.messages.v1.GetShortURLByOrganizationIDRequest\x1aE.shorturls.management.messages.v1.GetShortURLByOrganizationIDResponse\"Y\x92\xb5\x18\x0eshort-url:read\x82\xd3\xe4\x93\x02A\x12?/v1/organizations/{organization_id}/short-urls/{domain}/{alias}\x12\xf7\x01\n" +
	"\x1cListShortURLByOrganizationID\x12E.shorturls.management.messages.v1.ListShortURLByOrganizationIDRequest\x1aF.shorturls.management.messages.v1.ListShortURLByOrganizationIDResponse\"H\x92\xb5\x18\x0eshort-url:list\x82\xd3\xe4\x93\x020\x12./v1/organizations/{organization_id}/short-urls\x12\x9b\x02\n" +
	"\x1eUpdateShortURLByOrganizationID\x12G.shorturls.management.messages.v1.UpdateShortURLByOrganizationIDRequest\x1aH.shorturls.management.messages.v1.UpdateShortURLByOrganizationIDResponse\"f\x92\xb5\x18\x10short-url:update\x82\xd3\xe4\x93\x02L:\tshort_url2?/v1/organizations/{organization_id}/short-urls/{domain}/{alias}\x12\x90\x02\n" +
	"\x1eDeleteShortURLByOrganizationID\x12G.shorturls.management.messages.v1.DeleteShortURLByOrganizationIDRequest\x1aH.shorturls.management.messages.v1.DeleteShortURLByOrganizationIDResponse\"[\x92\xb5\x18\x10short-url:delete\x82\xd3\xe4\x93\x02A*?/v1/organizations/{organization_id}/short-urls/{domain}/{alias}B\xad\x02\n" +
	"#com.shorturls.management.service.v1B\fServiceProtoP\x01ZYgithub.com/FreibergVlad/url-shortener/proto/pkg/shorturls/management/service/v1;servicev1\xa2\x02\x03SMS\xaa\x02\x1fShorturls.Management.Service.V1\xca\x02\x1fShorturls\\Management\\Service\\V1\xe2\x02+Shorturls\\Management\\Service\\V1\\GPBMetadata\xea\x02\"Shorturls::Management::Service::V1b\x06proto3"

var file_shorturls_management_service_v1_service_proto_goTypes = []any{
	(*v1.GetShortURLRequest)(nil),                     // 0: shorturls.management.messages.v1.GetShortURLRequest
	(*v1.GetShortURLByOrganizationIDRequest)(nil),     // 1: shorturls.management.messages.v1.GetShortURLByOrganizationIDRequest
	(*v1.ListShortURLByOrganizationIDRequest)(nil),    // 2: shorturls.management.messages.v1.ListShortURLByOrganizationIDRequest
	(*v1.UpdateShortURLByOrganizationIDRequest)(nil),  // 3: shorturls.management.messages.v1.UpdateShortURLByOrganizationIDRequest
	(*v1.DeleteShortURLByOrganizationIDRequest)(nil),  // 4: shorturls.management.messages.v1.DeleteShortURLByOrganizationIDRequest
	(*v1.GetShortURLResponse)(nil),                    // 5: shorturls.management.messages.v1.GetShortURLResponse
	(*v1.GetShortURLByOrganizationIDResponse)(nil),    // 6: shorturls.management.messages.v1.GetShortURLByOrganizationIDResponse
	(*v1.ListShortURLByOrganizationIDResponse)(nil),   // 7: shorturls.management.messages.v1.ListShortURLByOrganizationIDResponse
	(*v1.UpdateShortURLByOrganizationIDResponse)(nil), // 8: shorturls.management.messages.v1.UpdateShortURLByOrganizationIDResponse
	(*v1.DeleteShortURLByOrganizationIDResponse)(nil), // 9: shorturls.management.messages.v1.DeleteShortURLByOrganizationIDResponse
}
var file_shorturls_management_service_v1_service_proto_depIdxs = []int32{
	0, // 0: shorturls.management.service.v1.ShortURLManagementService.GetShortURL:input_type -> shorturls.management.messages.v1.GetShortURLRequest
	1, // 1: shorturls.management.service.v1.ShortURLManagementService.GetShortURLByOrganizationID:input_type -> shorturls.management.messages.v1.GetShortURLByOrganizationIDRequest
	2, // 2: shorturls.management.service.v1.ShortURLManagementService.ListShortURLByOrganizationID:input_type -> shorturls.management.messages.v1.ListShortURLByOrganizationIDRequest
	3, // 3: shorturls.management.service.v1.ShortURLManagementService.UpdateShortURLByOrganizationID:input_type -> shorturls.management.messages.v1.UpdateShortURLByOrganizationIDRequest
	4, // 4: shorturls.management.service.v1.ShortURLManagementService.DeleteShortURLByOrganizationID:input_type -> shorturls.management.messages.v1.DeleteShortURLByOrganizationIDRequest
	5, // 5: shorturls.management.service.v1.ShortURLManagementService.GetShortURL:output_type -> shorturls.management.messages.v1.GetShortURLResponse
	6, // 6: shorturls.management.service.v1.ShortURLManagementService.GetShortURLByOrganizationID:output_type -> shorturls.management.messages.v1.GetShortURLByOrganizationIDResponse
	7, // 7: shorturls.management.service.v1.ShortURLManagementService.ListShortURLByOrganizationID:output_type -> shorturls.management.messages.v1.ListShortURLByOrganizationIDResponse
	8, // 8: shorturls.management.service.v1.ShortURLManagementService.UpdateShortURLByOrganizationID:output_type -> shorturls.management.messages.v1.UpdateShortURLByOrganizationIDResponse
	9, // 9: shorturls.management.service.v1.ShortURLManagementService.DeleteShortURLByOrganizationID:output_type -> shorturls.management.messages.v1.DeleteShortURLByOrganizationIDResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shorturls_management_service_v1_service_proto_init() }
func file_shorturls_management_service_v1_service_proto_init() {
	if File_shorturls_management_service_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shorturls_management_service_v1_service_proto_rawDesc), len(file_shorturls_management_service_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shorturls_management_service_v1_service_proto_goTypes,
		DependencyIndexes: file_shorturls_management_service_v1_service_proto_depIdxs,
	}.Build()
	File_shorturls_management_service_v1_service_proto = out.File
	file_shorturls_management_service_v1_service_proto_goTypes = nil
	file_shorturls_management_service_v1_service_proto_depIdxs = nil
}
