services:
  short-url-redirection-service:
    build:
      dockerfile: ./services/short-url-redirection-service/Dockerfile
    container_name: short-url-redirection-service
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - LOG_LEVEL=info
      - DOMAIN=localhost:8080
      - SHORT_URL_MANAGEMENT_SERVICE_DSN=short-url-management-service:8082
    depends_on:
      - short-url-management-service

  short-url-generator-service:
    build:
      dockerfile: ./services/short-url-management-service/docker/Dockerfile
      target: short-url-generator-service
    container_name: short-url-generator-service
    ports:
      - 8081:8081
    environment:
      - PORT=8081
      - LOG_LEVEL=info
      - SHORT_URL_ALIAS_LENGTH=4
      - SHORT_URL_SCHEME=http
      - MAX_RETRIES_ON_COLLISION=5
      - MONGO_DSN=mongodb://root:root@mongodb:27017/short-url-management-service?authSource=admin
      - MONGO_DB_NAME=short-url-management-service
      - REDIS_DSN=redis://:root@redis-cache:6379/0
      - AUTH_SERVICE_DSN=auth-service:8083
      - DOMAIN_SERVICE_DSN=domain-service:8084
    depends_on:
      - mongodb
      - redis-cache
      - auth-service
      - domain-service
      - short-url-service-migrations

  short-url-management-service:
    build:
      dockerfile: ./services/short-url-management-service/docker/Dockerfile
      target: short-url-management-service
    container_name: short-url-management-service
    ports:
      - 8082:8082
    environment:
      - PORT=8082
      - LOG_LEVEL=info
      - MONGO_DSN=mongodb://root:root@mongodb:27017/short-url-management-service?authSource=admin
      - MONGO_DB_NAME=short-url-management-service
      - REDIS_DSN=redis://:root@redis-cache:6379/0
      - AUTH_SERVICE_DSN=auth-service:8083
    depends_on:
      - mongodb
      - redis-cache
      - auth-service
      - short-url-service-migrations

  short-url-service-migrations:
    build:
      dockerfile: ./services/short-url-management-service/docker/Dockerfile
      target: migrations
    container_name: short-url-management-service-migrations
    environment:
      - LOG_LEVEL=info
      - MONGO_DSN=mongodb://root:root@mongodb:27017/short-url-management-service?authSource=admin
      - MONGO_DB_NAME=short-url-management-service
    depends_on:
      - mongodb

  auth-service:
    build:
      dockerfile: ./services/auth-service/docker/Dockerfile
      target: auth-service
    container_name: auth-service
    ports:
      - 8083:8083
    environment:
      - LOG_LEVEL=info
      - PORT=8083
      - JWT_SECRET=secret
      - JWT_REFRESH_SECRET=refresh-secret
      - JWT_LIFETIME_SECONDS=300
      - JWT_REFRESH_LIFETIME_SECONDS=86400
      - REDIS_DSN=redis://:root@redis-cache:6379/0
      - POSTGRES_DSN=postgresql://root:root@postgres:5432/auth-service
      - ADMIN_EMAIL=fake-admin@email.com
      - ADMIN_PASSWORD=123
    depends_on:
      postgres:
        condition: service_healthy

  auth-service-migrations:
    build:
      dockerfile: ./services/auth-service/docker/Dockerfile
      target: migrations
    container_name: auth-service-migrations
    environment:
      - LOG_LEVEL=info
      - MIGRATION_POSTGRES_DSN=pgx5://root:root@postgres:5432/auth-service
    depends_on:
      postgres:
        condition: service_healthy

  domain-service:
    build:
      dockerfile: ./services/domain-service/docker/Dockerfile
    container_name: domain-service
    ports:
      - 8084:8084
    environment:
      - PORT=8084
      - LOG_LEVEL=info
      - AUTH_SERVICE_DSN=auth-service:8083
      - PUBLIC_DOMAINS=localhost:8080
    depends_on:
      - auth-service

  api-gateway:
    build:
      dockerfile: ./services/api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - 8085:8085
    environment:
      - PORT=8085
      - LOG_LEVEL=info
      - JWT_SECRET=secret
      - SHORT_URL_GENERATOR_SERVICE_DSN=short-url-generator-service:8081
      - SHORT_URL_MANAGEMENT_SERVICE_DSN=short-url-management-service:8082
      - AUTH_SERVICE_DSN=auth-service:8083
      - DOMAIN_SERVICE_DSN=domain-service:8084
    depends_on:
      - short-url-management-service
      - short-url-generator-service
      - auth-service
      - domain-service

  redis-cache:
    image: redis:latest
    container_name: redis-cache
    restart: always
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=root
      - REDIS_PORT=6379
    tmpfs:
      - /data

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    tmpfs:
      - /data/db

  postgres:
    image: postgres:17.2
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=auth-service
    ports:
      - 5432:5432
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5