// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: invitations/messages/v1/invitation.proto

package messagesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InvitationStatus int32

const (
	InvitationStatus_INVITATION_STATUS_UNSPECIFIED InvitationStatus = 0
	InvitationStatus_INVITATION_STATUS_ACTIVE      InvitationStatus = 1
	InvitationStatus_INVITATION_STATUS_REDEEMED    InvitationStatus = 2
	InvitationStatus_INVITATION_STATUS_EXPIRED     InvitationStatus = 3
)

// Enum value maps for InvitationStatus.
var (
	InvitationStatus_name = map[int32]string{
		0: "INVITATION_STATUS_UNSPECIFIED",
		1: "INVITATION_STATUS_ACTIVE",
		2: "INVITATION_STATUS_REDEEMED",
		3: "INVITATION_STATUS_EXPIRED",
	}
	InvitationStatus_value = map[string]int32{
		"INVITATION_STATUS_UNSPECIFIED": 0,
		"INVITATION_STATUS_ACTIVE":      1,
		"INVITATION_STATUS_REDEEMED":    2,
		"INVITATION_STATUS_EXPIRED":     3,
	}
)

func (x InvitationStatus) Enum() *InvitationStatus {
	p := new(InvitationStatus)
	*p = x
	return p
}

func (x InvitationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InvitationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_invitations_messages_v1_invitation_proto_enumTypes[0].Descriptor()
}

func (InvitationStatus) Type() protoreflect.EnumType {
	return &file_invitations_messages_v1_invitation_proto_enumTypes[0]
}

func (x InvitationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InvitationStatus.Descriptor instead.
func (InvitationStatus) EnumDescriptor() ([]byte, []int) {
	return file_invitations_messages_v1_invitation_proto_rawDescGZIP(), []int{0}
}

type Invitation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Status         InvitationStatus       `protobuf:"varint,3,opt,name=status,proto3,enum=invitations.messages.v1.InvitationStatus" json:"status,omitempty"`
	Email          string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	RoleId         string                 `protobuf:"bytes,5,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CreatedBy      string                 `protobuf:"bytes,8,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Invitation) Reset() {
	*x = Invitation{}
	mi := &file_invitations_messages_v1_invitation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invitation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invitation) ProtoMessage() {}

func (x *Invitation) ProtoReflect() protoreflect.Message {
	mi := &file_invitations_messages_v1_invitation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invitation.ProtoReflect.Descriptor instead.
func (*Invitation) Descriptor() ([]byte, []int) {
	return file_invitations_messages_v1_invitation_proto_rawDescGZIP(), []int{0}
}

func (x *Invitation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Invitation) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Invitation) GetStatus() InvitationStatus {
	if x != nil {
		return x.Status
	}
	return InvitationStatus_INVITATION_STATUS_UNSPECIFIED
}

func (x *Invitation) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Invitation) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *Invitation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Invitation) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Invitation) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

var File_invitations_messages_v1_invitation_proto protoreflect.FileDescriptor

const file_invitations_messages_v1_invitation_proto_rawDesc = "" +
	"\n" +
	"(invitations/messages/v1/invitation.proto\x12\x17invitations.messages.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcc\x02\n" +
	"\n" +
	"Invitation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12A\n" +
	"\x06status\x18\x03 \x01(\x0e2).invitations.messages.v1.InvitationStatusR\x06status\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x17\n" +
	"\arole_id\x18\x05 \x01(\tR\x06roleId\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expires_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\b \x01(\tR\tcreatedBy*\x92\x01\n" +
	"\x10InvitationStatus\x12!\n" +
	"\x1dINVITATION_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18INVITATION_STATUS_ACTIVE\x10\x01\x12\x1e\n" +
	"\x1aINVITATION_STATUS_REDEEMED\x10\x02\x12\x1d\n" +
	"\x19INVITATION_STATUS_EXPIRED\x10\x03B\x80\x02\n" +
	"\x1bcom.invitations.messages.v1B\x0fInvitationProtoP\x01ZRgithub.com/FreibergVlad/url-shortener/proto/pkg/invitations/messages/v1;messagesv1\xa2\x02\x03IMX\xaa\x02\x17Invitations.Messages.V1\xca\x02\x17Invitations\\Messages\\V1\xe2\x02#Invitations\\Messages\\V1\\GPBMetadata\xea\x02\x19Invitations::Messages::V1b\x06proto3"

var (
	file_invitations_messages_v1_invitation_proto_rawDescOnce sync.Once
	file_invitations_messages_v1_invitation_proto_rawDescData []byte
)

func file_invitations_messages_v1_invitation_proto_rawDescGZIP() []byte {
	file_invitations_messages_v1_invitation_proto_rawDescOnce.Do(func() {
		file_invitations_messages_v1_invitation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_invitations_messages_v1_invitation_proto_rawDesc), len(file_invitations_messages_v1_invitation_proto_rawDesc)))
	})
	return file_invitations_messages_v1_invitation_proto_rawDescData
}

var file_invitations_messages_v1_invitation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_invitations_messages_v1_invitation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_invitations_messages_v1_invitation_proto_goTypes = []any{
	(InvitationStatus)(0),         // 0: invitations.messages.v1.InvitationStatus
	(*Invitation)(nil),            // 1: invitations.messages.v1.Invitation
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_invitations_messages_v1_invitation_proto_depIdxs = []int32{
	0, // 0: invitations.messages.v1.Invitation.status:type_name -> invitations.messages.v1.InvitationStatus
	2, // 1: invitations.messages.v1.Invitation.created_at:type_name -> google.protobuf.Timestamp
	2, // 2: invitations.messages.v1.Invitation.expires_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_invitations_messages_v1_invitation_proto_init() }
func file_invitations_messages_v1_invitation_proto_init() {
	if File_invitations_messages_v1_invitation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_invitations_messages_v1_invitation_proto_rawDesc), len(file_invitations_messages_v1_invitation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_invitations_messages_v1_invitation_proto_goTypes,
		DependencyIndexes: file_invitations_messages_v1_invitation_proto_depIdxs,
		EnumInfos:         file_invitations_messages_v1_invitation_proto_enumTypes,
		MessageInfos:      file_invitations_messages_v1_invitation_proto_msgTypes,
	}.Build()
	File_invitations_messages_v1_invitation_proto = out.File
	file_invitations_messages_v1_invitation_proto_goTypes = nil
	file_invitations_messages_v1_invitation_proto_depIdxs = nil
}
