// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: tokens/service/v1/service.proto

package servicev1

import (
	context "context"
	v1 "github.com/FreibergVlad/url-shortener/proto/pkg/tokens/messages/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TokenService_IssueAuthenticationToken_FullMethodName   = "/tokens.service.v1.TokenService/IssueAuthenticationToken"
	TokenService_RefreshAuthenticationToken_FullMethodName = "/tokens.service.v1.TokenService/RefreshAuthenticationToken"
)

// TokenServiceClient is the client API for TokenService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TokenServiceClient interface {
	IssueAuthenticationToken(ctx context.Context, in *v1.IssueAuthenticationTokenRequest, opts ...grpc.CallOption) (*v1.IssueAuthenticationTokenResponse, error)
	RefreshAuthenticationToken(ctx context.Context, in *v1.RefreshAuthenticationTokenRequest, opts ...grpc.CallOption) (*v1.RefreshAuthenticationTokenResponse, error)
}

type tokenServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenServiceClient(cc grpc.ClientConnInterface) TokenServiceClient {
	return &tokenServiceClient{cc}
}

func (c *tokenServiceClient) IssueAuthenticationToken(ctx context.Context, in *v1.IssueAuthenticationTokenRequest, opts ...grpc.CallOption) (*v1.IssueAuthenticationTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.IssueAuthenticationTokenResponse)
	err := c.cc.Invoke(ctx, TokenService_IssueAuthenticationToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenServiceClient) RefreshAuthenticationToken(ctx context.Context, in *v1.RefreshAuthenticationTokenRequest, opts ...grpc.CallOption) (*v1.RefreshAuthenticationTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.RefreshAuthenticationTokenResponse)
	err := c.cc.Invoke(ctx, TokenService_RefreshAuthenticationToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenServiceServer is the server API for TokenService service.
// All implementations must embed UnimplementedTokenServiceServer
// for forward compatibility.
type TokenServiceServer interface {
	IssueAuthenticationToken(context.Context, *v1.IssueAuthenticationTokenRequest) (*v1.IssueAuthenticationTokenResponse, error)
	RefreshAuthenticationToken(context.Context, *v1.RefreshAuthenticationTokenRequest) (*v1.RefreshAuthenticationTokenResponse, error)
	mustEmbedUnimplementedTokenServiceServer()
}

// UnimplementedTokenServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTokenServiceServer struct{}

func (UnimplementedTokenServiceServer) IssueAuthenticationToken(context.Context, *v1.IssueAuthenticationTokenRequest) (*v1.IssueAuthenticationTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IssueAuthenticationToken not implemented")
}
func (UnimplementedTokenServiceServer) RefreshAuthenticationToken(context.Context, *v1.RefreshAuthenticationTokenRequest) (*v1.RefreshAuthenticationTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshAuthenticationToken not implemented")
}
func (UnimplementedTokenServiceServer) mustEmbedUnimplementedTokenServiceServer() {}
func (UnimplementedTokenServiceServer) testEmbeddedByValue()                      {}

// UnsafeTokenServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TokenServiceServer will
// result in compilation errors.
type UnsafeTokenServiceServer interface {
	mustEmbedUnimplementedTokenServiceServer()
}

func RegisterTokenServiceServer(s grpc.ServiceRegistrar, srv TokenServiceServer) {
	// If the following call pancis, it indicates UnimplementedTokenServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TokenService_ServiceDesc, srv)
}

func _TokenService_IssueAuthenticationToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.IssueAuthenticationTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenServiceServer).IssueAuthenticationToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TokenService_IssueAuthenticationToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenServiceServer).IssueAuthenticationToken(ctx, req.(*v1.IssueAuthenticationTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenService_RefreshAuthenticationToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.RefreshAuthenticationTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenServiceServer).RefreshAuthenticationToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TokenService_RefreshAuthenticationToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenServiceServer).RefreshAuthenticationToken(ctx, req.(*v1.RefreshAuthenticationTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TokenService_ServiceDesc is the grpc.ServiceDesc for TokenService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TokenService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tokens.service.v1.TokenService",
	HandlerType: (*TokenServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IssueAuthenticationToken",
			Handler:    _TokenService_IssueAuthenticationToken_Handler,
		},
		{
			MethodName: "RefreshAuthenticationToken",
			Handler:    _TokenService_RefreshAuthenticationToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tokens/service/v1/service.proto",
}
