// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: tokens/service/v1/service.proto

package servicev1

import (
	_ "github.com/FreibergVlad/url-shortener/proto/pkg/permissions/messages/v1"
	v1 "github.com/FreibergVlad/url-shortener/proto/pkg/tokens/messages/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_tokens_service_v1_service_proto protoreflect.FileDescriptor

const file_tokens_service_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1ftokens/service/v1/service.proto\x12\x11tokens.service.v1\x1a\x1cgoogle/api/annotations.proto\x1a)permissions/messages/v1/permissions.proto\x1a;tokens/messages/v1/issue_authentication_token_request.proto\x1a<tokens/messages/v1/issue_authentication_token_response.proto\x1a=tokens/messages/v1/refresh_authentication_token_request.proto\x1a>tokens/messages/v1/refresh_authentication_token_response.proto2\xe8\x02\n" +
	"\fTokenService\x12\xa6\x01\n" +
	"\x18IssueAuthenticationToken\x123.tokens.messages.v1.IssueAuthenticationTokenRequest\x1a4.tokens.messages.v1.IssueAuthenticationTokenResponse\"\x1f\x8a\xb5\x18\x00\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/tokens/issue\x12\xae\x01\n" +
	"\x1aRefreshAuthenticationToken\x125.tokens.messages.v1.RefreshAuthenticationTokenRequest\x1a6.tokens.messages.v1.RefreshAuthenticationTokenResponse\"!\x8a\xb5\x18\x00\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/tokens/refreshB\xd8\x01\n" +
	"\x15com.tokens.service.v1B\fServiceProtoP\x01ZKgithub.com/FreibergVlad/url-shortener/proto/pkg/tokens/service/v1;servicev1\xa2\x02\x03TSX\xaa\x02\x11Tokens.Service.V1\xca\x02\x11Tokens\\Service\\V1\xe2\x02\x1dTokens\\Service\\V1\\GPBMetadata\xea\x02\x13Tokens::Service::V1b\x06proto3"

var file_tokens_service_v1_service_proto_goTypes = []any{
	(*v1.IssueAuthenticationTokenRequest)(nil),    // 0: tokens.messages.v1.IssueAuthenticationTokenRequest
	(*v1.RefreshAuthenticationTokenRequest)(nil),  // 1: tokens.messages.v1.RefreshAuthenticationTokenRequest
	(*v1.IssueAuthenticationTokenResponse)(nil),   // 2: tokens.messages.v1.IssueAuthenticationTokenResponse
	(*v1.RefreshAuthenticationTokenResponse)(nil), // 3: tokens.messages.v1.RefreshAuthenticationTokenResponse
}
var file_tokens_service_v1_service_proto_depIdxs = []int32{
	0, // 0: tokens.service.v1.TokenService.IssueAuthenticationToken:input_type -> tokens.messages.v1.IssueAuthenticationTokenRequest
	1, // 1: tokens.service.v1.TokenService.RefreshAuthenticationToken:input_type -> tokens.messages.v1.RefreshAuthenticationTokenRequest
	2, // 2: tokens.service.v1.TokenService.IssueAuthenticationToken:output_type -> tokens.messages.v1.IssueAuthenticationTokenResponse
	3, // 3: tokens.service.v1.TokenService.RefreshAuthenticationToken:output_type -> tokens.messages.v1.RefreshAuthenticationTokenResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tokens_service_v1_service_proto_init() }
func file_tokens_service_v1_service_proto_init() {
	if File_tokens_service_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tokens_service_v1_service_proto_rawDesc), len(file_tokens_service_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tokens_service_v1_service_proto_goTypes,
		DependencyIndexes: file_tokens_service_v1_service_proto_depIdxs,
	}.Build()
	File_tokens_service_v1_service_proto = out.File
	file_tokens_service_v1_service_proto_goTypes = nil
	file_tokens_service_v1_service_proto_depIdxs = nil
}
