// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: organizations/messages/v1/create_organization_request.proto

package messagesv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOrganizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrganizationRequest) Reset() {
	*x = CreateOrganizationRequest{}
	mi := &file_organizations_messages_v1_create_organization_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrganizationRequest) ProtoMessage() {}

func (x *CreateOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organizations_messages_v1_create_organization_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrganizationRequest.ProtoReflect.Descriptor instead.
func (*CreateOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_organizations_messages_v1_create_organization_request_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrganizationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateOrganizationRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

var File_organizations_messages_v1_create_organization_request_proto protoreflect.FileDescriptor

const file_organizations_messages_v1_create_organization_request_proto_rawDesc = "" +
	"\n" +
	";organizations/messages/v1/create_organization_request.proto\x12\x19organizations.messages.v1\x1a\x1bbuf/validate/validate.proto\"\xcc\x01\n" +
	"\x19CreateOrganizationRequest\x12 \n" +
	"\x04name\x18\x01 \x01(\tB\f\xbaH\t\xc8\x01\x01r\x04\x10\x02\x182R\x04name\x12\x8c\x01\n" +
	"\x04slug\x18\x02 \x01(\tBx\xbaHu\xba\x01i\n" +
	"\vslug_format\x12.'slug' can contain URL allowed characters only\x1a*this.matches('^[a-z0-9]+(?:-[a-z0-9]+)*$')\xc8\x01\x01r\x04\x10\x02\x182R\x04slugB\x9b\x02\n" +
	"\x1dcom.organizations.messages.v1B\x1eCreateOrganizationRequestProtoP\x01ZTgithub.com/FreibergVlad/url-shortener/proto/pkg/organizations/messages/v1;messagesv1\xa2\x02\x03OMX\xaa\x02\x19Organizations.Messages.V1\xca\x02\x19Organizations\\Messages\\V1\xe2\x02%Organizations\\Messages\\V1\\GPBMetadata\xea\x02\x1bOrganizations::Messages::V1b\x06proto3"

var (
	file_organizations_messages_v1_create_organization_request_proto_rawDescOnce sync.Once
	file_organizations_messages_v1_create_organization_request_proto_rawDescData []byte
)

func file_organizations_messages_v1_create_organization_request_proto_rawDescGZIP() []byte {
	file_organizations_messages_v1_create_organization_request_proto_rawDescOnce.Do(func() {
		file_organizations_messages_v1_create_organization_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_organizations_messages_v1_create_organization_request_proto_rawDesc), len(file_organizations_messages_v1_create_organization_request_proto_rawDesc)))
	})
	return file_organizations_messages_v1_create_organization_request_proto_rawDescData
}

var file_organizations_messages_v1_create_organization_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_organizations_messages_v1_create_organization_request_proto_goTypes = []any{
	(*CreateOrganizationRequest)(nil), // 0: organizations.messages.v1.CreateOrganizationRequest
}
var file_organizations_messages_v1_create_organization_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_organizations_messages_v1_create_organization_request_proto_init() }
func file_organizations_messages_v1_create_organization_request_proto_init() {
	if File_organizations_messages_v1_create_organization_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_organizations_messages_v1_create_organization_request_proto_rawDesc), len(file_organizations_messages_v1_create_organization_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_organizations_messages_v1_create_organization_request_proto_goTypes,
		DependencyIndexes: file_organizations_messages_v1_create_organization_request_proto_depIdxs,
		MessageInfos:      file_organizations_messages_v1_create_organization_request_proto_msgTypes,
	}.Build()
	File_organizations_messages_v1_create_organization_request_proto = out.File
	file_organizations_messages_v1_create_organization_request_proto_goTypes = nil
	file_organizations_messages_v1_create_organization_request_proto_depIdxs = nil
}
