// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: organizations/messages/v1/list_me_organization_memberships_response.proto

package messagesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListMeOrganizationMembershipsResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Data          []*OrganizationMembership `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMeOrganizationMembershipsResponse) Reset() {
	*x = ListMeOrganizationMembershipsResponse{}
	mi := &file_organizations_messages_v1_list_me_organization_memberships_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMeOrganizationMembershipsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMeOrganizationMembershipsResponse) ProtoMessage() {}

func (x *ListMeOrganizationMembershipsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_organizations_messages_v1_list_me_organization_memberships_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMeOrganizationMembershipsResponse.ProtoReflect.Descriptor instead.
func (*ListMeOrganizationMembershipsResponse) Descriptor() ([]byte, []int) {
	return file_organizations_messages_v1_list_me_organization_memberships_response_proto_rawDescGZIP(), []int{0}
}

func (x *ListMeOrganizationMembershipsResponse) GetData() []*OrganizationMembership {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_organizations_messages_v1_list_me_organization_memberships_response_proto protoreflect.FileDescriptor

const file_organizations_messages_v1_list_me_organization_memberships_response_proto_rawDesc = "" +
	"\n" +
	"Iorganizations/messages/v1/list_me_organization_memberships_response.proto\x12\x19organizations.messages.v1\x1a,organizations/messages/v1/organization.proto\"n\n" +
	"%ListMeOrganizationMembershipsResponse\x12E\n" +
	"\x04data\x18\x01 \x03(\v21.organizations.messages.v1.OrganizationMembershipR\x04dataB\xa7\x02\n" +
	"\x1dcom.organizations.messages.v1B*ListMeOrganizationMembershipsResponseProtoP\x01ZTgithub.com/FreibergVlad/url-shortener/proto/pkg/organizations/messages/v1;messagesv1\xa2\x02\x03OMX\xaa\x02\x19Organizations.Messages.V1\xca\x02\x19Organizations\\Messages\\V1\xe2\x02%Organizations\\Messages\\V1\\GPBMetadata\xea\x02\x1bOrganizations::Messages::V1b\x06proto3"

var (
	file_organizations_messages_v1_list_me_organization_memberships_response_proto_rawDescOnce sync.Once
	file_organizations_messages_v1_list_me_organization_memberships_response_proto_rawDescData []byte
)

func file_organizations_messages_v1_list_me_organization_memberships_response_proto_rawDescGZIP() []byte {
	file_organizations_messages_v1_list_me_organization_memberships_response_proto_rawDescOnce.Do(func() {
		file_organizations_messages_v1_list_me_organization_memberships_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_organizations_messages_v1_list_me_organization_memberships_response_proto_rawDesc), len(file_organizations_messages_v1_list_me_organization_memberships_response_proto_rawDesc)))
	})
	return file_organizations_messages_v1_list_me_organization_memberships_response_proto_rawDescData
}

var file_organizations_messages_v1_list_me_organization_memberships_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_organizations_messages_v1_list_me_organization_memberships_response_proto_goTypes = []any{
	(*ListMeOrganizationMembershipsResponse)(nil), // 0: organizations.messages.v1.ListMeOrganizationMembershipsResponse
	(*OrganizationMembership)(nil),                // 1: organizations.messages.v1.OrganizationMembership
}
var file_organizations_messages_v1_list_me_organization_memberships_response_proto_depIdxs = []int32{
	1, // 0: organizations.messages.v1.ListMeOrganizationMembershipsResponse.data:type_name -> organizations.messages.v1.OrganizationMembership
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_organizations_messages_v1_list_me_organization_memberships_response_proto_init() }
func file_organizations_messages_v1_list_me_organization_memberships_response_proto_init() {
	if File_organizations_messages_v1_list_me_organization_memberships_response_proto != nil {
		return
	}
	file_organizations_messages_v1_organization_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_organizations_messages_v1_list_me_organization_memberships_response_proto_rawDesc), len(file_organizations_messages_v1_list_me_organization_memberships_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_organizations_messages_v1_list_me_organization_memberships_response_proto_goTypes,
		DependencyIndexes: file_organizations_messages_v1_list_me_organization_memberships_response_proto_depIdxs,
		MessageInfos:      file_organizations_messages_v1_list_me_organization_memberships_response_proto_msgTypes,
	}.Build()
	File_organizations_messages_v1_list_me_organization_memberships_response_proto = out.File
	file_organizations_messages_v1_list_me_organization_memberships_response_proto_goTypes = nil
	file_organizations_messages_v1_list_me_organization_memberships_response_proto_depIdxs = nil
}
