// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: organizations/messages/v1/organization.proto

package messagesv1

import (
	v1 "github.com/FreibergVlad/url-shortener/proto/pkg/permissions/messages/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrganizationMembership struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organization  *ShortOrganization     `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	Role          *v1.Role               `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrganizationMembership) Reset() {
	*x = OrganizationMembership{}
	mi := &file_organizations_messages_v1_organization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationMembership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationMembership) ProtoMessage() {}

func (x *OrganizationMembership) ProtoReflect() protoreflect.Message {
	mi := &file_organizations_messages_v1_organization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationMembership.ProtoReflect.Descriptor instead.
func (*OrganizationMembership) Descriptor() ([]byte, []int) {
	return file_organizations_messages_v1_organization_proto_rawDescGZIP(), []int{0}
}

func (x *OrganizationMembership) GetOrganization() *ShortOrganization {
	if x != nil {
		return x.Organization
	}
	return nil
}

func (x *OrganizationMembership) GetRole() *v1.Role {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *OrganizationMembership) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ShortOrganization struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortOrganization) Reset() {
	*x = ShortOrganization{}
	mi := &file_organizations_messages_v1_organization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortOrganization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortOrganization) ProtoMessage() {}

func (x *ShortOrganization) ProtoReflect() protoreflect.Message {
	mi := &file_organizations_messages_v1_organization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortOrganization.ProtoReflect.Descriptor instead.
func (*ShortOrganization) Descriptor() ([]byte, []int) {
	return file_organizations_messages_v1_organization_proto_rawDescGZIP(), []int{1}
}

func (x *ShortOrganization) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ShortOrganization) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type Organization struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Organization) Reset() {
	*x = Organization{}
	mi := &file_organizations_messages_v1_organization_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Organization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Organization) ProtoMessage() {}

func (x *Organization) ProtoReflect() protoreflect.Message {
	mi := &file_organizations_messages_v1_organization_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Organization.ProtoReflect.Descriptor instead.
func (*Organization) Descriptor() ([]byte, []int) {
	return file_organizations_messages_v1_organization_proto_rawDescGZIP(), []int{2}
}

func (x *Organization) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Organization) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Organization) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Organization) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Organization) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

var File_organizations_messages_v1_organization_proto protoreflect.FileDescriptor

const file_organizations_messages_v1_organization_proto_rawDesc = "" +
	"\n" +
	",organizations/messages/v1/organization.proto\x12\x19organizations.messages.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\"permissions/messages/v1/role.proto\"\xd8\x01\n" +
	"\x16OrganizationMembership\x12P\n" +
	"\forganization\x18\x01 \x01(\v2,.organizations.messages.v1.ShortOrganizationR\forganization\x121\n" +
	"\x04role\x18\x02 \x01(\v2\x1d.permissions.messages.v1.RoleR\x04role\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"7\n" +
	"\x11ShortOrganization\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\"\xa0\x01\n" +
	"\fOrganization\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\x05 \x01(\tR\tcreatedByB\x8e\x02\n" +
	"\x1dcom.organizations.messages.v1B\x11OrganizationProtoP\x01ZTgithub.com/FreibergVlad/url-shortener/proto/pkg/organizations/messages/v1;messagesv1\xa2\x02\x03OMX\xaa\x02\x19Organizations.Messages.V1\xca\x02\x19Organizations\\Messages\\V1\xe2\x02%Organizations\\Messages\\V1\\GPBMetadata\xea\x02\x1bOrganizations::Messages::V1b\x06proto3"

var (
	file_organizations_messages_v1_organization_proto_rawDescOnce sync.Once
	file_organizations_messages_v1_organization_proto_rawDescData []byte
)

func file_organizations_messages_v1_organization_proto_rawDescGZIP() []byte {
	file_organizations_messages_v1_organization_proto_rawDescOnce.Do(func() {
		file_organizations_messages_v1_organization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_organizations_messages_v1_organization_proto_rawDesc), len(file_organizations_messages_v1_organization_proto_rawDesc)))
	})
	return file_organizations_messages_v1_organization_proto_rawDescData
}

var file_organizations_messages_v1_organization_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_organizations_messages_v1_organization_proto_goTypes = []any{
	(*OrganizationMembership)(nil), // 0: organizations.messages.v1.OrganizationMembership
	(*ShortOrganization)(nil),      // 1: organizations.messages.v1.ShortOrganization
	(*Organization)(nil),           // 2: organizations.messages.v1.Organization
	(*v1.Role)(nil),                // 3: permissions.messages.v1.Role
	(*timestamppb.Timestamp)(nil),  // 4: google.protobuf.Timestamp
}
var file_organizations_messages_v1_organization_proto_depIdxs = []int32{
	1, // 0: organizations.messages.v1.OrganizationMembership.organization:type_name -> organizations.messages.v1.ShortOrganization
	3, // 1: organizations.messages.v1.OrganizationMembership.role:type_name -> permissions.messages.v1.Role
	4, // 2: organizations.messages.v1.OrganizationMembership.created_at:type_name -> google.protobuf.Timestamp
	4, // 3: organizations.messages.v1.Organization.created_at:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_organizations_messages_v1_organization_proto_init() }
func file_organizations_messages_v1_organization_proto_init() {
	if File_organizations_messages_v1_organization_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_organizations_messages_v1_organization_proto_rawDesc), len(file_organizations_messages_v1_organization_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_organizations_messages_v1_organization_proto_goTypes,
		DependencyIndexes: file_organizations_messages_v1_organization_proto_depIdxs,
		MessageInfos:      file_organizations_messages_v1_organization_proto_msgTypes,
	}.Build()
	File_organizations_messages_v1_organization_proto = out.File
	file_organizations_messages_v1_organization_proto_goTypes = nil
	file_organizations_messages_v1_organization_proto_depIdxs = nil
}
