// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: shorturls/management/messages/v1/delete_short_url_by_org_id_request.proto

package messagesv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteShortURLByOrganizationIDRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Domain         string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Alias          string                 `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteShortURLByOrganizationIDRequest) Reset() {
	*x = DeleteShortURLByOrganizationIDRequest{}
	mi := &file_shorturls_management_messages_v1_delete_short_url_by_org_id_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShortURLByOrganizationIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShortURLByOrganizationIDRequest) ProtoMessage() {}

func (x *DeleteShortURLByOrganizationIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shorturls_management_messages_v1_delete_short_url_by_org_id_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShortURLByOrganizationIDRequest.ProtoReflect.Descriptor instead.
func (*DeleteShortURLByOrganizationIDRequest) Descriptor() ([]byte, []int) {
	return file_shorturls_management_messages_v1_delete_short_url_by_org_id_request_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteShortURLByOrganizationIDRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *DeleteShortURLByOrganizationIDRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *DeleteShortURLByOrganizationIDRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

var File_shorturls_management_messages_v1_delete_short_url_by_org_id_request_proto protoreflect.FileDescriptor

const file_shorturls_management_messages_v1_delete_short_url_by_org_id_request_proto_rawDesc = "" +
	"\n" +
	"Ishorturls/management/messages/v1/delete_short_url_by_org_id_request.proto\x12 shorturls.management.messages.v1\x1a\x1bbuf/validate/validate.proto\"\x9b\x01\n" +
	"%DeleteShortURLByOrganizationIDRequest\x124\n" +
	"\x0forganization_id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x0eorganizationId\x12\x1e\n" +
	"\x06domain\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x06domain\x12\x1c\n" +
	"\x05alias\x18\x03 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x05aliasB\xc9\x02\n" +
	"$com.shorturls.management.messages.v1B!DeleteShortUrlByOrgIdRequestProtoP\x01Z[github.com/FreibergVlad/url-shortener/proto/pkg/shorturls/management/messages/v1;messagesv1\xa2\x02\x03SMM\xaa\x02 Shorturls.Management.Messages.V1\xca\x02 Shorturls\\Management\\Messages\\V1\xe2\x02,Shorturls\\Management\\Messages\\V1\\GPBMetadata\xea\x02#Shorturls::Management::Messages::V1b\x06proto3"

var (
	file_shorturls_management_messages_v1_delete_short_url_by_org_id_request_proto_rawDescOnce sync.Once
	file_shorturls_management_messages_v1_delete_short_url_by_org_id_request_proto_rawDescData []byte
)

func file_shorturls_management_messages_v1_delete_short_url_by_org_id_request_proto_rawDescGZIP() []byte {
	file_shorturls_management_messages_v1_delete_short_url_by_org_id_request_proto_rawDescOnce.Do(func() {
		file_shorturls_management_messages_v1_delete_short_url_by_org_id_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shorturls_management_messages_v1_delete_short_url_by_org_id_request_proto_rawDesc), len(file_shorturls_management_messages_v1_delete_short_url_by_org_id_request_proto_rawDesc)))
	})
	return file_shorturls_management_messages_v1_delete_short_url_by_org_id_request_proto_rawDescData
}

var file_shorturls_management_messages_v1_delete_short_url_by_org_id_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_shorturls_management_messages_v1_delete_short_url_by_org_id_request_proto_goTypes = []any{
	(*DeleteShortURLByOrganizationIDRequest)(nil), // 0: shorturls.management.messages.v1.DeleteShortURLByOrganizationIDRequest
}
var file_shorturls_management_messages_v1_delete_short_url_by_org_id_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shorturls_management_messages_v1_delete_short_url_by_org_id_request_proto_init() }
func file_shorturls_management_messages_v1_delete_short_url_by_org_id_request_proto_init() {
	if File_shorturls_management_messages_v1_delete_short_url_by_org_id_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shorturls_management_messages_v1_delete_short_url_by_org_id_request_proto_rawDesc), len(file_shorturls_management_messages_v1_delete_short_url_by_org_id_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shorturls_management_messages_v1_delete_short_url_by_org_id_request_proto_goTypes,
		DependencyIndexes: file_shorturls_management_messages_v1_delete_short_url_by_org_id_request_proto_depIdxs,
		MessageInfos:      file_shorturls_management_messages_v1_delete_short_url_by_org_id_request_proto_msgTypes,
	}.Build()
	File_shorturls_management_messages_v1_delete_short_url_by_org_id_request_proto = out.File
	file_shorturls_management_messages_v1_delete_short_url_by_org_id_request_proto_goTypes = nil
	file_shorturls_management_messages_v1_delete_short_url_by_org_id_request_proto_depIdxs = nil
}
