// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: shorturls/management/messages/v1/list_short_url_by_org_id_response.proto

package messagesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListShortURLByOrganizationIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*ShortURL            `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShortURLByOrganizationIDResponse) Reset() {
	*x = ListShortURLByOrganizationIDResponse{}
	mi := &file_shorturls_management_messages_v1_list_short_url_by_org_id_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShortURLByOrganizationIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShortURLByOrganizationIDResponse) ProtoMessage() {}

func (x *ListShortURLByOrganizationIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shorturls_management_messages_v1_list_short_url_by_org_id_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShortURLByOrganizationIDResponse.ProtoReflect.Descriptor instead.
func (*ListShortURLByOrganizationIDResponse) Descriptor() ([]byte, []int) {
	return file_shorturls_management_messages_v1_list_short_url_by_org_id_response_proto_rawDescGZIP(), []int{0}
}

func (x *ListShortURLByOrganizationIDResponse) GetData() []*ShortURL {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListShortURLByOrganizationIDResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_shorturls_management_messages_v1_list_short_url_by_org_id_response_proto protoreflect.FileDescriptor

const file_shorturls_management_messages_v1_list_short_url_by_org_id_response_proto_rawDesc = "" +
	"\n" +
	"Hshorturls/management/messages/v1/list_short_url_by_org_id_response.proto\x12 shorturls.management.messages.v1\x1a0shorturls/management/messages/v1/short_url.proto\"|\n" +
	"$ListShortURLByOrganizationIDResponse\x12>\n" +
	"\x04data\x18\x01 \x03(\v2*.shorturls.management.messages.v1.ShortURLR\x04data\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05totalB\xc8\x02\n" +
	"$com.shorturls.management.messages.v1B ListShortUrlByOrgIdResponseProtoP\x01Z[github.com/FreibergVlad/url-shortener/proto/pkg/shorturls/management/messages/v1;messagesv1\xa2\x02\x03SMM\xaa\x02 Shorturls.Management.Messages.V1\xca\x02 Shorturls\\Management\\Messages\\V1\xe2\x02,Shorturls\\Management\\Messages\\V1\\GPBMetadata\xea\x02#Shorturls::Management::Messages::V1b\x06proto3"

var (
	file_shorturls_management_messages_v1_list_short_url_by_org_id_response_proto_rawDescOnce sync.Once
	file_shorturls_management_messages_v1_list_short_url_by_org_id_response_proto_rawDescData []byte
)

func file_shorturls_management_messages_v1_list_short_url_by_org_id_response_proto_rawDescGZIP() []byte {
	file_shorturls_management_messages_v1_list_short_url_by_org_id_response_proto_rawDescOnce.Do(func() {
		file_shorturls_management_messages_v1_list_short_url_by_org_id_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shorturls_management_messages_v1_list_short_url_by_org_id_response_proto_rawDesc), len(file_shorturls_management_messages_v1_list_short_url_by_org_id_response_proto_rawDesc)))
	})
	return file_shorturls_management_messages_v1_list_short_url_by_org_id_response_proto_rawDescData
}

var file_shorturls_management_messages_v1_list_short_url_by_org_id_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_shorturls_management_messages_v1_list_short_url_by_org_id_response_proto_goTypes = []any{
	(*ListShortURLByOrganizationIDResponse)(nil), // 0: shorturls.management.messages.v1.ListShortURLByOrganizationIDResponse
	(*ShortURL)(nil), // 1: shorturls.management.messages.v1.ShortURL
}
var file_shorturls_management_messages_v1_list_short_url_by_org_id_response_proto_depIdxs = []int32{
	1, // 0: shorturls.management.messages.v1.ListShortURLByOrganizationIDResponse.data:type_name -> shorturls.management.messages.v1.ShortURL
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_shorturls_management_messages_v1_list_short_url_by_org_id_response_proto_init() }
func file_shorturls_management_messages_v1_list_short_url_by_org_id_response_proto_init() {
	if File_shorturls_management_messages_v1_list_short_url_by_org_id_response_proto != nil {
		return
	}
	file_shorturls_management_messages_v1_short_url_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shorturls_management_messages_v1_list_short_url_by_org_id_response_proto_rawDesc), len(file_shorturls_management_messages_v1_list_short_url_by_org_id_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shorturls_management_messages_v1_list_short_url_by_org_id_response_proto_goTypes,
		DependencyIndexes: file_shorturls_management_messages_v1_list_short_url_by_org_id_response_proto_depIdxs,
		MessageInfos:      file_shorturls_management_messages_v1_list_short_url_by_org_id_response_proto_msgTypes,
	}.Build()
	File_shorturls_management_messages_v1_list_short_url_by_org_id_response_proto = out.File
	file_shorturls_management_messages_v1_list_short_url_by_org_id_response_proto_goTypes = nil
	file_shorturls_management_messages_v1_list_short_url_by_org_id_response_proto_depIdxs = nil
}
