// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: shorturls/management/messages/v1/list_short_url_by_org_id_request.proto

package messagesv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListShortURLByOrganizationIDRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	PageNum        int32                  `protobuf:"varint,2,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize       int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListShortURLByOrganizationIDRequest) Reset() {
	*x = ListShortURLByOrganizationIDRequest{}
	mi := &file_shorturls_management_messages_v1_list_short_url_by_org_id_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShortURLByOrganizationIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShortURLByOrganizationIDRequest) ProtoMessage() {}

func (x *ListShortURLByOrganizationIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shorturls_management_messages_v1_list_short_url_by_org_id_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShortURLByOrganizationIDRequest.ProtoReflect.Descriptor instead.
func (*ListShortURLByOrganizationIDRequest) Descriptor() ([]byte, []int) {
	return file_shorturls_management_messages_v1_list_short_url_by_org_id_request_proto_rawDescGZIP(), []int{0}
}

func (x *ListShortURLByOrganizationIDRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ListShortURLByOrganizationIDRequest) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *ListShortURLByOrganizationIDRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_shorturls_management_messages_v1_list_short_url_by_org_id_request_proto protoreflect.FileDescriptor

const file_shorturls_management_messages_v1_list_short_url_by_org_id_request_proto_rawDesc = "" +
	"\n" +
	"Gshorturls/management/messages/v1/list_short_url_by_org_id_request.proto\x12 shorturls.management.messages.v1\x1a\x1bbuf/validate/validate.proto\"\xad\x01\n" +
	"#ListShortURLByOrganizationIDRequest\x124\n" +
	"\x0forganization_id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x0eorganizationId\x12%\n" +
	"\bpage_num\x18\x02 \x01(\x05B\n" +
	"\xbaH\a\xc8\x01\x01\x1a\x02(\x01R\apageNum\x12)\n" +
	"\tpage_size\x18\x03 \x01(\x05B\f\xbaH\t\xc8\x01\x01\x1a\x04\x18d(\x01R\bpageSizeB\xc7\x02\n" +
	"$com.shorturls.management.messages.v1B\x1fListShortUrlByOrgIdRequestProtoP\x01Z[github.com/FreibergVlad/url-shortener/proto/pkg/shorturls/management/messages/v1;messagesv1\xa2\x02\x03SMM\xaa\x02 Shorturls.Management.Messages.V1\xca\x02 Shorturls\\Management\\Messages\\V1\xe2\x02,Shorturls\\Management\\Messages\\V1\\GPBMetadata\xea\x02#Shorturls::Management::Messages::V1b\x06proto3"

var (
	file_shorturls_management_messages_v1_list_short_url_by_org_id_request_proto_rawDescOnce sync.Once
	file_shorturls_management_messages_v1_list_short_url_by_org_id_request_proto_rawDescData []byte
)

func file_shorturls_management_messages_v1_list_short_url_by_org_id_request_proto_rawDescGZIP() []byte {
	file_shorturls_management_messages_v1_list_short_url_by_org_id_request_proto_rawDescOnce.Do(func() {
		file_shorturls_management_messages_v1_list_short_url_by_org_id_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shorturls_management_messages_v1_list_short_url_by_org_id_request_proto_rawDesc), len(file_shorturls_management_messages_v1_list_short_url_by_org_id_request_proto_rawDesc)))
	})
	return file_shorturls_management_messages_v1_list_short_url_by_org_id_request_proto_rawDescData
}

var file_shorturls_management_messages_v1_list_short_url_by_org_id_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_shorturls_management_messages_v1_list_short_url_by_org_id_request_proto_goTypes = []any{
	(*ListShortURLByOrganizationIDRequest)(nil), // 0: shorturls.management.messages.v1.ListShortURLByOrganizationIDRequest
}
var file_shorturls_management_messages_v1_list_short_url_by_org_id_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shorturls_management_messages_v1_list_short_url_by_org_id_request_proto_init() }
func file_shorturls_management_messages_v1_list_short_url_by_org_id_request_proto_init() {
	if File_shorturls_management_messages_v1_list_short_url_by_org_id_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shorturls_management_messages_v1_list_short_url_by_org_id_request_proto_rawDesc), len(file_shorturls_management_messages_v1_list_short_url_by_org_id_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shorturls_management_messages_v1_list_short_url_by_org_id_request_proto_goTypes,
		DependencyIndexes: file_shorturls_management_messages_v1_list_short_url_by_org_id_request_proto_depIdxs,
		MessageInfos:      file_shorturls_management_messages_v1_list_short_url_by_org_id_request_proto_msgTypes,
	}.Build()
	File_shorturls_management_messages_v1_list_short_url_by_org_id_request_proto = out.File
	file_shorturls_management_messages_v1_list_short_url_by_org_id_request_proto_goTypes = nil
	file_shorturls_management_messages_v1_list_short_url_by_org_id_request_proto_depIdxs = nil
}
