// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: shorturls/management/messages/v1/short_url.proto

package messagesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LongURL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Assembled     string                 `protobuf:"bytes,2,opt,name=assembled,proto3" json:"assembled,omitempty"`
	Scheme        string                 `protobuf:"bytes,3,opt,name=scheme,proto3" json:"scheme,omitempty"`
	Host          string                 `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	Path          string                 `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	Query         string                 `protobuf:"bytes,6,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LongURL) Reset() {
	*x = LongURL{}
	mi := &file_shorturls_management_messages_v1_short_url_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LongURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LongURL) ProtoMessage() {}

func (x *LongURL) ProtoReflect() protoreflect.Message {
	mi := &file_shorturls_management_messages_v1_short_url_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LongURL.ProtoReflect.Descriptor instead.
func (*LongURL) Descriptor() ([]byte, []int) {
	return file_shorturls_management_messages_v1_short_url_proto_rawDescGZIP(), []int{0}
}

func (x *LongURL) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *LongURL) GetAssembled() string {
	if x != nil {
		return x.Assembled
	}
	return ""
}

func (x *LongURL) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *LongURL) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *LongURL) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *LongURL) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_shorturls_management_messages_v1_short_url_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_shorturls_management_messages_v1_short_url_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_shorturls_management_messages_v1_short_url_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ShortURL struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	LongUrl        *LongURL               `protobuf:"bytes,2,opt,name=long_url,json=longUrl,proto3" json:"long_url,omitempty"`
	ShortUrl       string                 `protobuf:"bytes,3,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	Domain         string                 `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain,omitempty"`
	Alias          string                 `protobuf:"bytes,5,opt,name=alias,proto3" json:"alias,omitempty"`
	ExpiresAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy      *User                  `protobuf:"bytes,8,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	Description    string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	Tags           []string               `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ShortURL) Reset() {
	*x = ShortURL{}
	mi := &file_shorturls_management_messages_v1_short_url_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortURL) ProtoMessage() {}

func (x *ShortURL) ProtoReflect() protoreflect.Message {
	mi := &file_shorturls_management_messages_v1_short_url_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortURL.ProtoReflect.Descriptor instead.
func (*ShortURL) Descriptor() ([]byte, []int) {
	return file_shorturls_management_messages_v1_short_url_proto_rawDescGZIP(), []int{2}
}

func (x *ShortURL) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ShortURL) GetLongUrl() *LongURL {
	if x != nil {
		return x.LongUrl
	}
	return nil
}

func (x *ShortURL) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *ShortURL) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ShortURL) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *ShortURL) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *ShortURL) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ShortURL) GetCreatedBy() *User {
	if x != nil {
		return x.CreatedBy
	}
	return nil
}

func (x *ShortURL) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ShortURL) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_shorturls_management_messages_v1_short_url_proto protoreflect.FileDescriptor

const file_shorturls_management_messages_v1_short_url_proto_rawDesc = "" +
	"\n" +
	"0shorturls/management/messages/v1/short_url.proto\x12 shorturls.management.messages.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x91\x01\n" +
	"\aLongURL\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x1c\n" +
	"\tassembled\x18\x02 \x01(\tR\tassembled\x12\x16\n" +
	"\x06scheme\x18\x03 \x01(\tR\x06scheme\x12\x12\n" +
	"\x04host\x18\x04 \x01(\tR\x04host\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\x12\x14\n" +
	"\x05query\x18\x06 \x01(\tR\x05query\",\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"\xb7\x03\n" +
	"\bShortURL\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12D\n" +
	"\blong_url\x18\x02 \x01(\v2).shorturls.management.messages.v1.LongURLR\alongUrl\x12\x1b\n" +
	"\tshort_url\x18\x03 \x01(\tR\bshortUrl\x12\x16\n" +
	"\x06domain\x18\x04 \x01(\tR\x06domain\x12\x14\n" +
	"\x05alias\x18\x05 \x01(\tR\x05alias\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12E\n" +
	"\n" +
	"created_by\x18\b \x01(\v2&.shorturls.management.messages.v1.UserR\tcreatedBy\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\n" +
	" \x03(\tR\x04tagsB\xb5\x02\n" +
	"$com.shorturls.management.messages.v1B\rShortUrlProtoP\x01Z[github.com/FreibergVlad/url-shortener/proto/pkg/shorturls/management/messages/v1;messagesv1\xa2\x02\x03SMM\xaa\x02 Shorturls.Management.Messages.V1\xca\x02 Shorturls\\Management\\Messages\\V1\xe2\x02,Shorturls\\Management\\Messages\\V1\\GPBMetadata\xea\x02#Shorturls::Management::Messages::V1b\x06proto3"

var (
	file_shorturls_management_messages_v1_short_url_proto_rawDescOnce sync.Once
	file_shorturls_management_messages_v1_short_url_proto_rawDescData []byte
)

func file_shorturls_management_messages_v1_short_url_proto_rawDescGZIP() []byte {
	file_shorturls_management_messages_v1_short_url_proto_rawDescOnce.Do(func() {
		file_shorturls_management_messages_v1_short_url_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shorturls_management_messages_v1_short_url_proto_rawDesc), len(file_shorturls_management_messages_v1_short_url_proto_rawDesc)))
	})
	return file_shorturls_management_messages_v1_short_url_proto_rawDescData
}

var file_shorturls_management_messages_v1_short_url_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_shorturls_management_messages_v1_short_url_proto_goTypes = []any{
	(*LongURL)(nil),               // 0: shorturls.management.messages.v1.LongURL
	(*User)(nil),                  // 1: shorturls.management.messages.v1.User
	(*ShortURL)(nil),              // 2: shorturls.management.messages.v1.ShortURL
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_shorturls_management_messages_v1_short_url_proto_depIdxs = []int32{
	0, // 0: shorturls.management.messages.v1.ShortURL.long_url:type_name -> shorturls.management.messages.v1.LongURL
	3, // 1: shorturls.management.messages.v1.ShortURL.expires_at:type_name -> google.protobuf.Timestamp
	3, // 2: shorturls.management.messages.v1.ShortURL.created_at:type_name -> google.protobuf.Timestamp
	1, // 3: shorturls.management.messages.v1.ShortURL.created_by:type_name -> shorturls.management.messages.v1.User
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_shorturls_management_messages_v1_short_url_proto_init() }
func file_shorturls_management_messages_v1_short_url_proto_init() {
	if File_shorturls_management_messages_v1_short_url_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shorturls_management_messages_v1_short_url_proto_rawDesc), len(file_shorturls_management_messages_v1_short_url_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shorturls_management_messages_v1_short_url_proto_goTypes,
		DependencyIndexes: file_shorturls_management_messages_v1_short_url_proto_depIdxs,
		MessageInfos:      file_shorturls_management_messages_v1_short_url_proto_msgTypes,
	}.Build()
	File_shorturls_management_messages_v1_short_url_proto = out.File
	file_shorturls_management_messages_v1_short_url_proto_goTypes = nil
	file_shorturls_management_messages_v1_short_url_proto_depIdxs = nil
}
