// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: shorturls/management/messages/v1/update_short_url_by_org_id_request.proto

package messagesv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateShortURLParams struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Alias         *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	LongUrl       string                  `protobuf:"bytes,2,opt,name=long_url,json=longUrl,proto3" json:"long_url,omitempty"` // validated at application level
	Description   string                  `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ExpiresAt     *timestamppb.Timestamp  `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Tags          []string                `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateShortURLParams) Reset() {
	*x = UpdateShortURLParams{}
	mi := &file_shorturls_management_messages_v1_update_short_url_by_org_id_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateShortURLParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShortURLParams) ProtoMessage() {}

func (x *UpdateShortURLParams) ProtoReflect() protoreflect.Message {
	mi := &file_shorturls_management_messages_v1_update_short_url_by_org_id_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShortURLParams.ProtoReflect.Descriptor instead.
func (*UpdateShortURLParams) Descriptor() ([]byte, []int) {
	return file_shorturls_management_messages_v1_update_short_url_by_org_id_request_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateShortURLParams) GetAlias() *wrapperspb.StringValue {
	if x != nil {
		return x.Alias
	}
	return nil
}

func (x *UpdateShortURLParams) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

func (x *UpdateShortURLParams) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateShortURLParams) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *UpdateShortURLParams) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type UpdateShortURLByOrganizationIDRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Domain         string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Alias          string                 `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`
	ShortUrl       *UpdateShortURLParams  `protobuf:"bytes,4,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	UpdateMask     *fieldmaskpb.FieldMask `protobuf:"bytes,5,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateShortURLByOrganizationIDRequest) Reset() {
	*x = UpdateShortURLByOrganizationIDRequest{}
	mi := &file_shorturls_management_messages_v1_update_short_url_by_org_id_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateShortURLByOrganizationIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShortURLByOrganizationIDRequest) ProtoMessage() {}

func (x *UpdateShortURLByOrganizationIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shorturls_management_messages_v1_update_short_url_by_org_id_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShortURLByOrganizationIDRequest.ProtoReflect.Descriptor instead.
func (*UpdateShortURLByOrganizationIDRequest) Descriptor() ([]byte, []int) {
	return file_shorturls_management_messages_v1_update_short_url_by_org_id_request_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateShortURLByOrganizationIDRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *UpdateShortURLByOrganizationIDRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *UpdateShortURLByOrganizationIDRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *UpdateShortURLByOrganizationIDRequest) GetShortUrl() *UpdateShortURLParams {
	if x != nil {
		return x.ShortUrl
	}
	return nil
}

func (x *UpdateShortURLByOrganizationIDRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

var File_shorturls_management_messages_v1_update_short_url_by_org_id_request_proto protoreflect.FileDescriptor

const file_shorturls_management_messages_v1_update_short_url_by_org_id_request_proto_rawDesc = "" +
	"\n" +
	"Ishorturls/management/messages/v1/update_short_url_by_org_id_request.proto\x12 shorturls.management.messages.v1\x1a\x1bbuf/validate/validate.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x99\x02\n" +
	"\x14UpdateShortURLParams\x12M\n" +
	"\x05alias\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueB\x19\xbaH\x16r\x14\x10\x04\x18\x1e2\x0e^[A-Za-z0-9]+$R\x05alias\x12\x19\n" +
	"\blong_url\x18\x02 \x01(\tR\alongUrl\x12*\n" +
	"\vdescription\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x18\xe8\aR\vdescription\x12C\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\b\xbaH\x05\xb2\x01\x02@\x01R\texpiresAt\x12&\n" +
	"\x04tags\x18\x05 \x03(\tB\x12\xbaH\x0f\x92\x01\f\x10\n" +
	"\x18\x01\"\x06r\x04\x10\x01\x182R\x04tags\"\xe3\x03\n" +
	"%UpdateShortURLByOrganizationIDRequest\x124\n" +
	"\x0forganization_id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x0eorganizationId\x12\x1e\n" +
	"\x06domain\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x06domain\x12\x1c\n" +
	"\x05alias\x18\x03 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x05alias\x12[\n" +
	"\tshort_url\x18\x04 \x01(\v26.shorturls.management.messages.v1.UpdateShortURLParamsB\x06\xbaH\x03\xc8\x01\x01R\bshortUrl\x12\xe8\x01\n" +
	"\vupdate_mask\x18\x05 \x01(\v2\x1a.google.protobuf.FieldMaskB\xaa\x01\xbaH\xa6\x01\xba\x01\x9f\x01\n" +
	"\x11valid_update_mask\x120a field mask path must contain only valid fields\x1aXthis.paths.all(path, path in ['alias', 'long_url', 'description', 'expires_at', 'tags'])\xc8\x01\x01R\n" +
	"updateMaskB\xc9\x02\n" +
	"$com.shorturls.management.messages.v1B!UpdateShortUrlByOrgIdRequestProtoP\x01Z[github.com/FreibergVlad/url-shortener/proto/pkg/shorturls/management/messages/v1;messagesv1\xa2\x02\x03SMM\xaa\x02 Shorturls.Management.Messages.V1\xca\x02 Shorturls\\Management\\Messages\\V1\xe2\x02,Shorturls\\Management\\Messages\\V1\\GPBMetadata\xea\x02#Shorturls::Management::Messages::V1b\x06proto3"

var (
	file_shorturls_management_messages_v1_update_short_url_by_org_id_request_proto_rawDescOnce sync.Once
	file_shorturls_management_messages_v1_update_short_url_by_org_id_request_proto_rawDescData []byte
)

func file_shorturls_management_messages_v1_update_short_url_by_org_id_request_proto_rawDescGZIP() []byte {
	file_shorturls_management_messages_v1_update_short_url_by_org_id_request_proto_rawDescOnce.Do(func() {
		file_shorturls_management_messages_v1_update_short_url_by_org_id_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shorturls_management_messages_v1_update_short_url_by_org_id_request_proto_rawDesc), len(file_shorturls_management_messages_v1_update_short_url_by_org_id_request_proto_rawDesc)))
	})
	return file_shorturls_management_messages_v1_update_short_url_by_org_id_request_proto_rawDescData
}

var file_shorturls_management_messages_v1_update_short_url_by_org_id_request_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_shorturls_management_messages_v1_update_short_url_by_org_id_request_proto_goTypes = []any{
	(*UpdateShortURLParams)(nil),                  // 0: shorturls.management.messages.v1.UpdateShortURLParams
	(*UpdateShortURLByOrganizationIDRequest)(nil), // 1: shorturls.management.messages.v1.UpdateShortURLByOrganizationIDRequest
	(*wrapperspb.StringValue)(nil),                // 2: google.protobuf.StringValue
	(*timestamppb.Timestamp)(nil),                 // 3: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),                 // 4: google.protobuf.FieldMask
}
var file_shorturls_management_messages_v1_update_short_url_by_org_id_request_proto_depIdxs = []int32{
	2, // 0: shorturls.management.messages.v1.UpdateShortURLParams.alias:type_name -> google.protobuf.StringValue
	3, // 1: shorturls.management.messages.v1.UpdateShortURLParams.expires_at:type_name -> google.protobuf.Timestamp
	0, // 2: shorturls.management.messages.v1.UpdateShortURLByOrganizationIDRequest.short_url:type_name -> shorturls.management.messages.v1.UpdateShortURLParams
	4, // 3: shorturls.management.messages.v1.UpdateShortURLByOrganizationIDRequest.update_mask:type_name -> google.protobuf.FieldMask
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_shorturls_management_messages_v1_update_short_url_by_org_id_request_proto_init() }
func file_shorturls_management_messages_v1_update_short_url_by_org_id_request_proto_init() {
	if File_shorturls_management_messages_v1_update_short_url_by_org_id_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shorturls_management_messages_v1_update_short_url_by_org_id_request_proto_rawDesc), len(file_shorturls_management_messages_v1_update_short_url_by_org_id_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shorturls_management_messages_v1_update_short_url_by_org_id_request_proto_goTypes,
		DependencyIndexes: file_shorturls_management_messages_v1_update_short_url_by_org_id_request_proto_depIdxs,
		MessageInfos:      file_shorturls_management_messages_v1_update_short_url_by_org_id_request_proto_msgTypes,
	}.Build()
	File_shorturls_management_messages_v1_update_short_url_by_org_id_request_proto = out.File
	file_shorturls_management_messages_v1_update_short_url_by_org_id_request_proto_goTypes = nil
	file_shorturls_management_messages_v1_update_short_url_by_org_id_request_proto_depIdxs = nil
}
