// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: permissions/service/v1/service.proto

package servicev1

import (
	v1 "github.com/FreibergVlad/url-shortener/proto/pkg/permissions/messages/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_permissions_service_v1_service_proto protoreflect.FileDescriptor

const file_permissions_service_v1_service_proto_rawDesc = "" +
	"\n" +
	"$permissions/service/v1/service.proto\x12\x16permissions.service.v1\x1a5permissions/messages/v1/has_permissions_request.proto\x1a6permissions/messages/v1/has_permissions_response.proto2\x86\x01\n" +
	"\x11PermissionService\x12q\n" +
	"\x0eHasPermissions\x12..permissions.messages.v1.HasPermissionsRequest\x1a/.permissions.messages.v1.HasPermissionsResponseB\xf6\x01\n" +
	"\x1acom.permissions.service.v1B\fServiceProtoP\x01ZPgithub.com/FreibergVlad/url-shortener/proto/pkg/permissions/service/v1;servicev1\xa2\x02\x03PSX\xaa\x02\x16Permissions.Service.V1\xca\x02\x16Permissions\\Service\\V1\xe2\x02\"Permissions\\Service\\V1\\GPBMetadata\xea\x02\x18Permissions::Service::V1b\x06proto3"

var file_permissions_service_v1_service_proto_goTypes = []any{
	(*v1.HasPermissionsRequest)(nil),  // 0: permissions.messages.v1.HasPermissionsRequest
	(*v1.HasPermissionsResponse)(nil), // 1: permissions.messages.v1.HasPermissionsResponse
}
var file_permissions_service_v1_service_proto_depIdxs = []int32{
	0, // 0: permissions.service.v1.PermissionService.HasPermissions:input_type -> permissions.messages.v1.HasPermissionsRequest
	1, // 1: permissions.service.v1.PermissionService.HasPermissions:output_type -> permissions.messages.v1.HasPermissionsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_permissions_service_v1_service_proto_init() }
func file_permissions_service_v1_service_proto_init() {
	if File_permissions_service_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_permissions_service_v1_service_proto_rawDesc), len(file_permissions_service_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_permissions_service_v1_service_proto_goTypes,
		DependencyIndexes: file_permissions_service_v1_service_proto_depIdxs,
	}.Build()
	File_permissions_service_v1_service_proto = out.File
	file_permissions_service_v1_service_proto_goTypes = nil
	file_permissions_service_v1_service_proto_depIdxs = nil
}
