// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: permissions/messages/v1/has_permissions_response.proto

package messagesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HasPermissionsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HasPermissions bool                   `protobuf:"varint,1,opt,name=has_permissions,json=hasPermissions,proto3" json:"has_permissions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HasPermissionsResponse) Reset() {
	*x = HasPermissionsResponse{}
	mi := &file_permissions_messages_v1_has_permissions_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasPermissionsResponse) ProtoMessage() {}

func (x *HasPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_permissions_messages_v1_has_permissions_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasPermissionsResponse.ProtoReflect.Descriptor instead.
func (*HasPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_permissions_messages_v1_has_permissions_response_proto_rawDescGZIP(), []int{0}
}

func (x *HasPermissionsResponse) GetHasPermissions() bool {
	if x != nil {
		return x.HasPermissions
	}
	return false
}

var File_permissions_messages_v1_has_permissions_response_proto protoreflect.FileDescriptor

const file_permissions_messages_v1_has_permissions_response_proto_rawDesc = "" +
	"\n" +
	"6permissions/messages/v1/has_permissions_response.proto\x12\x17permissions.messages.v1\x1a google/protobuf/descriptor.proto\"A\n" +
	"\x16HasPermissionsResponse\x12'\n" +
	"\x0fhas_permissions\x18\x01 \x01(\bR\x0ehasPermissionsB\x8c\x02\n" +
	"\x1bcom.permissions.messages.v1B\x1bHasPermissionsResponseProtoP\x01ZRgithub.com/FreibergVlad/url-shortener/proto/pkg/permissions/messages/v1;messagesv1\xa2\x02\x03PMX\xaa\x02\x17Permissions.Messages.V1\xca\x02\x17Permissions\\Messages\\V1\xe2\x02#Permissions\\Messages\\V1\\GPBMetadata\xea\x02\x19Permissions::Messages::V1b\x06proto3"

var (
	file_permissions_messages_v1_has_permissions_response_proto_rawDescOnce sync.Once
	file_permissions_messages_v1_has_permissions_response_proto_rawDescData []byte
)

func file_permissions_messages_v1_has_permissions_response_proto_rawDescGZIP() []byte {
	file_permissions_messages_v1_has_permissions_response_proto_rawDescOnce.Do(func() {
		file_permissions_messages_v1_has_permissions_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_permissions_messages_v1_has_permissions_response_proto_rawDesc), len(file_permissions_messages_v1_has_permissions_response_proto_rawDesc)))
	})
	return file_permissions_messages_v1_has_permissions_response_proto_rawDescData
}

var file_permissions_messages_v1_has_permissions_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_permissions_messages_v1_has_permissions_response_proto_goTypes = []any{
	(*HasPermissionsResponse)(nil), // 0: permissions.messages.v1.HasPermissionsResponse
}
var file_permissions_messages_v1_has_permissions_response_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_permissions_messages_v1_has_permissions_response_proto_init() }
func file_permissions_messages_v1_has_permissions_response_proto_init() {
	if File_permissions_messages_v1_has_permissions_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_permissions_messages_v1_has_permissions_response_proto_rawDesc), len(file_permissions_messages_v1_has_permissions_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_permissions_messages_v1_has_permissions_response_proto_goTypes,
		DependencyIndexes: file_permissions_messages_v1_has_permissions_response_proto_depIdxs,
		MessageInfos:      file_permissions_messages_v1_has_permissions_response_proto_msgTypes,
	}.Build()
	File_permissions_messages_v1_has_permissions_response_proto = out.File
	file_permissions_messages_v1_has_permissions_response_proto_goTypes = nil
	file_permissions_messages_v1_has_permissions_response_proto_depIdxs = nil
}
