// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: permissions/messages/v1/permissions.proto

package messagesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_permissions_messages_v1_permissions_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*wrapperspb.BoolValue)(nil),
		Field:         50001,
		Name:          "permissions.messages.v1.authentication_required",
		Tag:           "bytes,50001,opt,name=authentication_required",
		Filename:      "permissions/messages/v1/permissions.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: ([]string)(nil),
		Field:         50002,
		Name:          "permissions.messages.v1.required_permissions",
		Tag:           "bytes,50002,rep,name=required_permissions",
		Filename:      "permissions/messages/v1/permissions.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional google.protobuf.BoolValue authentication_required = 50001;
	E_AuthenticationRequired = &file_permissions_messages_v1_permissions_proto_extTypes[0]
	// repeated string required_permissions = 50002;
	E_RequiredPermissions = &file_permissions_messages_v1_permissions_proto_extTypes[1]
)

var File_permissions_messages_v1_permissions_proto protoreflect.FileDescriptor

const file_permissions_messages_v1_permissions_proto_rawDesc = "" +
	"\n" +
	")permissions/messages/v1/permissions.proto\x12\x17permissions.messages.v1\x1a google/protobuf/descriptor.proto\x1a\x1egoogle/protobuf/wrappers.proto:u\n" +
	"\x17authentication_required\x12\x1e.google.protobuf.MethodOptions\x18ц\x03 \x01(\v2\x1a.google.protobuf.BoolValueR\x16authenticationRequired:S\n" +
	"\x14required_permissions\x12\x1e.google.protobuf.MethodOptions\x18҆\x03 \x03(\tR\x13requiredPermissionsB\x81\x02\n" +
	"\x1bcom.permissions.messages.v1B\x10PermissionsProtoP\x01ZRgithub.com/FreibergVlad/url-shortener/proto/pkg/permissions/messages/v1;messagesv1\xa2\x02\x03PMX\xaa\x02\x17Permissions.Messages.V1\xca\x02\x17Permissions\\Messages\\V1\xe2\x02#Permissions\\Messages\\V1\\GPBMetadata\xea\x02\x19Permissions::Messages::V1b\x06proto3"

var file_permissions_messages_v1_permissions_proto_goTypes = []any{
	(*descriptorpb.MethodOptions)(nil), // 0: google.protobuf.MethodOptions
	(*wrapperspb.BoolValue)(nil),       // 1: google.protobuf.BoolValue
}
var file_permissions_messages_v1_permissions_proto_depIdxs = []int32{
	0, // 0: permissions.messages.v1.authentication_required:extendee -> google.protobuf.MethodOptions
	0, // 1: permissions.messages.v1.required_permissions:extendee -> google.protobuf.MethodOptions
	1, // 2: permissions.messages.v1.authentication_required:type_name -> google.protobuf.BoolValue
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	2, // [2:3] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_permissions_messages_v1_permissions_proto_init() }
func file_permissions_messages_v1_permissions_proto_init() {
	if File_permissions_messages_v1_permissions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_permissions_messages_v1_permissions_proto_rawDesc), len(file_permissions_messages_v1_permissions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_permissions_messages_v1_permissions_proto_goTypes,
		DependencyIndexes: file_permissions_messages_v1_permissions_proto_depIdxs,
		ExtensionInfos:    file_permissions_messages_v1_permissions_proto_extTypes,
	}.Build()
	File_permissions_messages_v1_permissions_proto = out.File
	file_permissions_messages_v1_permissions_proto_goTypes = nil
	file_permissions_messages_v1_permissions_proto_depIdxs = nil
}
