// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: organizations/service/v1/service.proto

package servicev1

import (
	v1 "github.com/FreibergVlad/url-shortener/proto/pkg/organizations/messages/v1"
	_ "github.com/FreibergVlad/url-shortener/proto/pkg/permissions/messages/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_organizations_service_v1_service_proto protoreflect.FileDescriptor

const file_organizations_service_v1_service_proto_rawDesc = "" +
	"\n" +
	"&organizations/service/v1/service.proto\x12\x18organizations.service.v1\x1a\x1cgoogle/api/annotations.proto\x1a;organizations/messages/v1/create_organization_request.proto\x1a<organizations/messages/v1/create_organization_response.proto\x1aHorganizations/messages/v1/list_me_organization_memberships_request.proto\x1aIorganizations/messages/v1/list_me_organization_memberships_response.proto\x1a)permissions/messages/v1/permissions.proto2\xb7\x03\n" +
	"\x13OrganizationService\x12\xb6\x01\n" +
	"\x12CreateOrganization\x124.organizations.messages.v1.CreateOrganizationRequest\x1a5.organizations.messages.v1.CreateOrganizationResponse\"3\x92\xb5\x18\x13organization:create\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/organizations\x12\xe6\x01\n" +
	"\x1dListMeOrganizationMemberships\x12?.organizations.messages.v1.ListMeOrganizationMembershipsRequest\x1a@.organizations.messages.v1.ListMeOrganizationMembershipsResponse\"B\x92\xb5\x18\x1corganization-membership:list\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/users/me/organizationsB\x82\x02\n" +
	"\x1ccom.organizations.service.v1B\fServiceProtoP\x01ZRgithub.com/FreibergVlad/url-shortener/proto/pkg/organizations/service/v1;servicev1\xa2\x02\x03OSX\xaa\x02\x18Organizations.Service.V1\xca\x02\x18Organizations\\Service\\V1\xe2\x02$Organizations\\Service\\V1\\GPBMetadata\xea\x02\x1aOrganizations::Service::V1b\x06proto3"

var file_organizations_service_v1_service_proto_goTypes = []any{
	(*v1.CreateOrganizationRequest)(nil),             // 0: organizations.messages.v1.CreateOrganizationRequest
	(*v1.ListMeOrganizationMembershipsRequest)(nil),  // 1: organizations.messages.v1.ListMeOrganizationMembershipsRequest
	(*v1.CreateOrganizationResponse)(nil),            // 2: organizations.messages.v1.CreateOrganizationResponse
	(*v1.ListMeOrganizationMembershipsResponse)(nil), // 3: organizations.messages.v1.ListMeOrganizationMembershipsResponse
}
var file_organizations_service_v1_service_proto_depIdxs = []int32{
	0, // 0: organizations.service.v1.OrganizationService.CreateOrganization:input_type -> organizations.messages.v1.CreateOrganizationRequest
	1, // 1: organizations.service.v1.OrganizationService.ListMeOrganizationMemberships:input_type -> organizations.messages.v1.ListMeOrganizationMembershipsRequest
	2, // 2: organizations.service.v1.OrganizationService.CreateOrganization:output_type -> organizations.messages.v1.CreateOrganizationResponse
	3, // 3: organizations.service.v1.OrganizationService.ListMeOrganizationMemberships:output_type -> organizations.messages.v1.ListMeOrganizationMembershipsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_organizations_service_v1_service_proto_init() }
func file_organizations_service_v1_service_proto_init() {
	if File_organizations_service_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_organizations_service_v1_service_proto_rawDesc), len(file_organizations_service_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_organizations_service_v1_service_proto_goTypes,
		DependencyIndexes: file_organizations_service_v1_service_proto_depIdxs,
	}.Build()
	File_organizations_service_v1_service_proto = out.File
	file_organizations_service_v1_service_proto_goTypes = nil
	file_organizations_service_v1_service_proto_depIdxs = nil
}
