// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: users/messages/v1/create_user_request.proto

package messagesv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_users_messages_v1_create_user_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_messages_v1_create_user_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_users_messages_v1_create_user_request_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_users_messages_v1_create_user_request_proto protoreflect.FileDescriptor

const file_users_messages_v1_create_user_request_proto_rawDesc = "" +
	"\n" +
	"+users/messages/v1/create_user_request.proto\x12\x11users.messages.v1\x1a\x1bbuf/validate/validate.proto\"\xc7\x01\n" +
	"\x11CreateUserRequest\x12c\n" +
	"\x05email\x18\x01 \x01(\tBM\xbaHJ\xba\x01D\n" +
	"\vvalid_email\x12%'email' must be a valid email address\x1a\x0ethis.isEmail()\xc8\x01\x01R\x05email\x12#\n" +
	"\tfull_name\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\bfullName\x12(\n" +
	"\bpassword\x18\x03 \x01(\tB\f\xbaH\t\xc8\x01\x01r\x04\x10\x03\x18HR\bpasswordB\xe3\x01\n" +
	"\x15com.users.messages.v1B\x16CreateUserRequestProtoP\x01ZLgithub.com/FreibergVlad/url-shortener/proto/pkg/users/messages/v1;messagesv1\xa2\x02\x03UMX\xaa\x02\x11Users.Messages.V1\xca\x02\x11Users\\Messages\\V1\xe2\x02\x1dUsers\\Messages\\V1\\GPBMetadata\xea\x02\x13Users::Messages::V1b\x06proto3"

var (
	file_users_messages_v1_create_user_request_proto_rawDescOnce sync.Once
	file_users_messages_v1_create_user_request_proto_rawDescData []byte
)

func file_users_messages_v1_create_user_request_proto_rawDescGZIP() []byte {
	file_users_messages_v1_create_user_request_proto_rawDescOnce.Do(func() {
		file_users_messages_v1_create_user_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_users_messages_v1_create_user_request_proto_rawDesc), len(file_users_messages_v1_create_user_request_proto_rawDesc)))
	})
	return file_users_messages_v1_create_user_request_proto_rawDescData
}

var file_users_messages_v1_create_user_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_users_messages_v1_create_user_request_proto_goTypes = []any{
	(*CreateUserRequest)(nil), // 0: users.messages.v1.CreateUserRequest
}
var file_users_messages_v1_create_user_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_users_messages_v1_create_user_request_proto_init() }
func file_users_messages_v1_create_user_request_proto_init() {
	if File_users_messages_v1_create_user_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_users_messages_v1_create_user_request_proto_rawDesc), len(file_users_messages_v1_create_user_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_users_messages_v1_create_user_request_proto_goTypes,
		DependencyIndexes: file_users_messages_v1_create_user_request_proto_depIdxs,
		MessageInfos:      file_users_messages_v1_create_user_request_proto_msgTypes,
	}.Build()
	File_users_messages_v1_create_user_request_proto = out.File
	file_users_messages_v1_create_user_request_proto_goTypes = nil
	file_users_messages_v1_create_user_request_proto_depIdxs = nil
}
