// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: users/messages/v1/get_me_response.proto

package messagesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeResponse) Reset() {
	*x = GetMeResponse{}
	mi := &file_users_messages_v1_get_me_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeResponse) ProtoMessage() {}

func (x *GetMeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_messages_v1_get_me_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeResponse.ProtoReflect.Descriptor instead.
func (*GetMeResponse) Descriptor() ([]byte, []int) {
	return file_users_messages_v1_get_me_response_proto_rawDescGZIP(), []int{0}
}

func (x *GetMeResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_users_messages_v1_get_me_response_proto protoreflect.FileDescriptor

const file_users_messages_v1_get_me_response_proto_rawDesc = "" +
	"\n" +
	"'users/messages/v1/get_me_response.proto\x12\x11users.messages.v1\x1a\x1cusers/messages/v1/user.proto\"<\n" +
	"\rGetMeResponse\x12+\n" +
	"\x04user\x18\x01 \x01(\v2\x17.users.messages.v1.UserR\x04userB\xdf\x01\n" +
	"\x15com.users.messages.v1B\x12GetMeResponseProtoP\x01ZLgithub.com/FreibergVlad/url-shortener/proto/pkg/users/messages/v1;messagesv1\xa2\x02\x03UMX\xaa\x02\x11Users.Messages.V1\xca\x02\x11Users\\Messages\\V1\xe2\x02\x1dUsers\\Messages\\V1\\GPBMetadata\xea\x02\x13Users::Messages::V1b\x06proto3"

var (
	file_users_messages_v1_get_me_response_proto_rawDescOnce sync.Once
	file_users_messages_v1_get_me_response_proto_rawDescData []byte
)

func file_users_messages_v1_get_me_response_proto_rawDescGZIP() []byte {
	file_users_messages_v1_get_me_response_proto_rawDescOnce.Do(func() {
		file_users_messages_v1_get_me_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_users_messages_v1_get_me_response_proto_rawDesc), len(file_users_messages_v1_get_me_response_proto_rawDesc)))
	})
	return file_users_messages_v1_get_me_response_proto_rawDescData
}

var file_users_messages_v1_get_me_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_users_messages_v1_get_me_response_proto_goTypes = []any{
	(*GetMeResponse)(nil), // 0: users.messages.v1.GetMeResponse
	(*User)(nil),          // 1: users.messages.v1.User
}
var file_users_messages_v1_get_me_response_proto_depIdxs = []int32{
	1, // 0: users.messages.v1.GetMeResponse.user:type_name -> users.messages.v1.User
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_users_messages_v1_get_me_response_proto_init() }
func file_users_messages_v1_get_me_response_proto_init() {
	if File_users_messages_v1_get_me_response_proto != nil {
		return
	}
	file_users_messages_v1_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_users_messages_v1_get_me_response_proto_rawDesc), len(file_users_messages_v1_get_me_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_users_messages_v1_get_me_response_proto_goTypes,
		DependencyIndexes: file_users_messages_v1_get_me_response_proto_depIdxs,
		MessageInfos:      file_users_messages_v1_get_me_response_proto_msgTypes,
	}.Build()
	File_users_messages_v1_get_me_response_proto = out.File
	file_users_messages_v1_get_me_response_proto_goTypes = nil
	file_users_messages_v1_get_me_response_proto_depIdxs = nil
}
