// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: users/service/v1/service.proto

package servicev1

import (
	_ "github.com/FreibergVlad/url-shortener/proto/pkg/permissions/messages/v1"
	v1 "github.com/FreibergVlad/url-shortener/proto/pkg/users/messages/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_users_service_v1_service_proto protoreflect.FileDescriptor

const file_users_service_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1eusers/service/v1/service.proto\x12\x10users.service.v1\x1a\x1cgoogle/api/annotations.proto\x1a)permissions/messages/v1/permissions.proto\x1a+users/messages/v1/create_user_request.proto\x1a,users/messages/v1/create_user_response.proto\x1a&users/messages/v1/get_me_request.proto\x1a'users/messages/v1/get_me_response.proto2\xef\x01\n" +
	"\vUserService\x12s\n" +
	"\n" +
	"CreateUser\x12$.users.messages.v1.CreateUserRequest\x1a%.users.messages.v1.CreateUserResponse\"\x18\x8a\xb5\x18\x00\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/users\x12k\n" +
	"\x05GetMe\x12\x1f.users.messages.v1.GetMeRequest\x1a .users.messages.v1.GetMeResponse\"\x1f\x92\xb5\x18\ame:read\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/users/meB\xd2\x01\n" +
	"\x14com.users.service.v1B\fServiceProtoP\x01ZJgithub.com/FreibergVlad/url-shortener/proto/pkg/users/service/v1;servicev1\xa2\x02\x03USX\xaa\x02\x10Users.Service.V1\xca\x02\x10Users\\Service\\V1\xe2\x02\x1cUsers\\Service\\V1\\GPBMetadata\xea\x02\x12Users::Service::V1b\x06proto3"

var file_users_service_v1_service_proto_goTypes = []any{
	(*v1.CreateUserRequest)(nil),  // 0: users.messages.v1.CreateUserRequest
	(*v1.GetMeRequest)(nil),       // 1: users.messages.v1.GetMeRequest
	(*v1.CreateUserResponse)(nil), // 2: users.messages.v1.CreateUserResponse
	(*v1.GetMeResponse)(nil),      // 3: users.messages.v1.GetMeResponse
}
var file_users_service_v1_service_proto_depIdxs = []int32{
	0, // 0: users.service.v1.UserService.CreateUser:input_type -> users.messages.v1.CreateUserRequest
	1, // 1: users.service.v1.UserService.GetMe:input_type -> users.messages.v1.GetMeRequest
	2, // 2: users.service.v1.UserService.CreateUser:output_type -> users.messages.v1.CreateUserResponse
	3, // 3: users.service.v1.UserService.GetMe:output_type -> users.messages.v1.GetMeResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_users_service_v1_service_proto_init() }
func file_users_service_v1_service_proto_init() {
	if File_users_service_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_users_service_v1_service_proto_rawDesc), len(file_users_service_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_users_service_v1_service_proto_goTypes,
		DependencyIndexes: file_users_service_v1_service_proto_depIdxs,
	}.Build()
	File_users_service_v1_service_proto = out.File
	file_users_service_v1_service_proto_goTypes = nil
	file_users_service_v1_service_proto_depIdxs = nil
}
