// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: domains/service/v1/service.proto

package servicev1

import (
	v1 "github.com/FreibergVlad/url-shortener/proto/pkg/domains/messages/v1"
	_ "github.com/FreibergVlad/url-shortener/proto/pkg/permissions/messages/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_domains_service_v1_service_proto protoreflect.FileDescriptor

const file_domains_service_v1_service_proto_rawDesc = "" +
	"\n" +
	" domains/service/v1/service.proto\x12\x12domains.service.v1\x1a:domains/messages/v1/list_organization_domain_request.proto\x1a;domains/messages/v1/list_organization_domain_response.proto\x1a\x1cgoogle/api/annotations.proto\x1a)permissions/messages/v1/permissions.proto2\xd7\x01\n" +
	"\rDomainService\x12\xc5\x01\n" +
	"\x16ListOrganizationDomain\x122.domains.messages.v1.ListOrganizationDomainRequest\x1a3.domains.messages.v1.ListOrganizationDomainResponse\"B\x92\xb5\x18\vdomain:list\x82\xd3\xe4\x93\x02-\x12+/v1/organizations/{organization_id}/domainsB\xde\x01\n" +
	"\x16com.domains.service.v1B\fServiceProtoP\x01ZLgithub.com/FreibergVlad/url-shortener/proto/pkg/domains/service/v1;servicev1\xa2\x02\x03DSX\xaa\x02\x12Domains.Service.V1\xca\x02\x12Domains\\Service\\V1\xe2\x02\x1eDomains\\Service\\V1\\GPBMetadata\xea\x02\x14Domains::Service::V1b\x06proto3"

var file_domains_service_v1_service_proto_goTypes = []any{
	(*v1.ListOrganizationDomainRequest)(nil),  // 0: domains.messages.v1.ListOrganizationDomainRequest
	(*v1.ListOrganizationDomainResponse)(nil), // 1: domains.messages.v1.ListOrganizationDomainResponse
}
var file_domains_service_v1_service_proto_depIdxs = []int32{
	0, // 0: domains.service.v1.DomainService.ListOrganizationDomain:input_type -> domains.messages.v1.ListOrganizationDomainRequest
	1, // 1: domains.service.v1.DomainService.ListOrganizationDomain:output_type -> domains.messages.v1.ListOrganizationDomainResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_domains_service_v1_service_proto_init() }
func file_domains_service_v1_service_proto_init() {
	if File_domains_service_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domains_service_v1_service_proto_rawDesc), len(file_domains_service_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_domains_service_v1_service_proto_goTypes,
		DependencyIndexes: file_domains_service_v1_service_proto_depIdxs,
	}.Build()
	File_domains_service_v1_service_proto = out.File
	file_domains_service_v1_service_proto_goTypes = nil
	file_domains_service_v1_service_proto_depIdxs = nil
}
