// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: shorturls/generator/messages/v1/create_short_url_request.proto

package messagesv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateShortURLRequest struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	OrganizationId string                  `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Domain         string                  `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Alias          *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`
	LongUrl        string                  `protobuf:"bytes,4,opt,name=long_url,json=longUrl,proto3" json:"long_url,omitempty"` // validated at application level
	Tags           []string                `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	ExpiresAt      *timestamppb.Timestamp  `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Description    string                  `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateShortURLRequest) Reset() {
	*x = CreateShortURLRequest{}
	mi := &file_shorturls_generator_messages_v1_create_short_url_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortURLRequest) ProtoMessage() {}

func (x *CreateShortURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shorturls_generator_messages_v1_create_short_url_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortURLRequest.ProtoReflect.Descriptor instead.
func (*CreateShortURLRequest) Descriptor() ([]byte, []int) {
	return file_shorturls_generator_messages_v1_create_short_url_request_proto_rawDescGZIP(), []int{0}
}

func (x *CreateShortURLRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CreateShortURLRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *CreateShortURLRequest) GetAlias() *wrapperspb.StringValue {
	if x != nil {
		return x.Alias
	}
	return nil
}

func (x *CreateShortURLRequest) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

func (x *CreateShortURLRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateShortURLRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *CreateShortURLRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_shorturls_generator_messages_v1_create_short_url_request_proto protoreflect.FileDescriptor

const file_shorturls_generator_messages_v1_create_short_url_request_proto_rawDesc = "" +
	"\n" +
	">shorturls/generator/messages/v1/create_short_url_request.proto\x12\x1fshorturls.generator.messages.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xf8\x02\n" +
	"\x15CreateShortURLRequest\x124\n" +
	"\x0forganization_id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x0eorganizationId\x12\x1e\n" +
	"\x06domain\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x06domain\x12M\n" +
	"\x05alias\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueB\x19\xbaH\x16r\x14\x10\x04\x18\x1e2\x0e^[A-Za-z0-9]+$R\x05alias\x12!\n" +
	"\blong_url\x18\x04 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\alongUrl\x12&\n" +
	"\x04tags\x18\x05 \x03(\tB\x12\xbaH\x0f\x92\x01\f\x10\n" +
	"\x18\x01\"\x06r\x04\x10\x01\x182R\x04tags\x12C\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\b\xbaH\x05\xb2\x01\x02@\x01R\texpiresAt\x12*\n" +
	"\vdescription\x18\a \x01(\tB\b\xbaH\x05r\x03\x18\xe8\aR\vdescriptionB\xbe\x02\n" +
	"#com.shorturls.generator.messages.v1B\x1aCreateShortUrlRequestProtoP\x01ZZgithub.com/FreibergVlad/url-shortener/proto/pkg/shorturls/generator/messages/v1;messagesv1\xa2\x02\x03SGM\xaa\x02\x1fShorturls.Generator.Messages.V1\xca\x02 Shorturls\\Generator_\\Messages\\V1\xe2\x02,Shorturls\\Generator_\\Messages\\V1\\GPBMetadata\xea\x02\"Shorturls::Generator::Messages::V1b\x06proto3"

var (
	file_shorturls_generator_messages_v1_create_short_url_request_proto_rawDescOnce sync.Once
	file_shorturls_generator_messages_v1_create_short_url_request_proto_rawDescData []byte
)

func file_shorturls_generator_messages_v1_create_short_url_request_proto_rawDescGZIP() []byte {
	file_shorturls_generator_messages_v1_create_short_url_request_proto_rawDescOnce.Do(func() {
		file_shorturls_generator_messages_v1_create_short_url_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shorturls_generator_messages_v1_create_short_url_request_proto_rawDesc), len(file_shorturls_generator_messages_v1_create_short_url_request_proto_rawDesc)))
	})
	return file_shorturls_generator_messages_v1_create_short_url_request_proto_rawDescData
}

var file_shorturls_generator_messages_v1_create_short_url_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_shorturls_generator_messages_v1_create_short_url_request_proto_goTypes = []any{
	(*CreateShortURLRequest)(nil),  // 0: shorturls.generator.messages.v1.CreateShortURLRequest
	(*wrapperspb.StringValue)(nil), // 1: google.protobuf.StringValue
	(*timestamppb.Timestamp)(nil),  // 2: google.protobuf.Timestamp
}
var file_shorturls_generator_messages_v1_create_short_url_request_proto_depIdxs = []int32{
	1, // 0: shorturls.generator.messages.v1.CreateShortURLRequest.alias:type_name -> google.protobuf.StringValue
	2, // 1: shorturls.generator.messages.v1.CreateShortURLRequest.expires_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_shorturls_generator_messages_v1_create_short_url_request_proto_init() }
func file_shorturls_generator_messages_v1_create_short_url_request_proto_init() {
	if File_shorturls_generator_messages_v1_create_short_url_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shorturls_generator_messages_v1_create_short_url_request_proto_rawDesc), len(file_shorturls_generator_messages_v1_create_short_url_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shorturls_generator_messages_v1_create_short_url_request_proto_goTypes,
		DependencyIndexes: file_shorturls_generator_messages_v1_create_short_url_request_proto_depIdxs,
		MessageInfos:      file_shorturls_generator_messages_v1_create_short_url_request_proto_msgTypes,
	}.Build()
	File_shorturls_generator_messages_v1_create_short_url_request_proto = out.File
	file_shorturls_generator_messages_v1_create_short_url_request_proto_goTypes = nil
	file_shorturls_generator_messages_v1_create_short_url_request_proto_depIdxs = nil
}
