// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: tokens/messages/v1/issue_authentication_token_request.proto

package messagesv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IssueAuthenticationTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueAuthenticationTokenRequest) Reset() {
	*x = IssueAuthenticationTokenRequest{}
	mi := &file_tokens_messages_v1_issue_authentication_token_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueAuthenticationTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueAuthenticationTokenRequest) ProtoMessage() {}

func (x *IssueAuthenticationTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tokens_messages_v1_issue_authentication_token_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueAuthenticationTokenRequest.ProtoReflect.Descriptor instead.
func (*IssueAuthenticationTokenRequest) Descriptor() ([]byte, []int) {
	return file_tokens_messages_v1_issue_authentication_token_request_proto_rawDescGZIP(), []int{0}
}

func (x *IssueAuthenticationTokenRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *IssueAuthenticationTokenRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_tokens_messages_v1_issue_authentication_token_request_proto protoreflect.FileDescriptor

const file_tokens_messages_v1_issue_authentication_token_request_proto_rawDesc = "" +
	"\n" +
	";tokens/messages/v1/issue_authentication_token_request.proto\x12\x12tokens.messages.v1\x1a\x1bbuf/validate/validate.proto\"c\n" +
	"\x1fIssueAuthenticationTokenRequest\x12\x1c\n" +
	"\x05email\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x05email\x12\"\n" +
	"\bpassword\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\bpasswordB\xf7\x01\n" +
	"\x16com.tokens.messages.v1B$IssueAuthenticationTokenRequestProtoP\x01ZMgithub.com/FreibergVlad/url-shortener/proto/pkg/tokens/messages/v1;messagesv1\xa2\x02\x03TMX\xaa\x02\x12Tokens.Messages.V1\xca\x02\x12Tokens\\Messages\\V1\xe2\x02\x1eTokens\\Messages\\V1\\GPBMetadata\xea\x02\x14Tokens::Messages::V1b\x06proto3"

var (
	file_tokens_messages_v1_issue_authentication_token_request_proto_rawDescOnce sync.Once
	file_tokens_messages_v1_issue_authentication_token_request_proto_rawDescData []byte
)

func file_tokens_messages_v1_issue_authentication_token_request_proto_rawDescGZIP() []byte {
	file_tokens_messages_v1_issue_authentication_token_request_proto_rawDescOnce.Do(func() {
		file_tokens_messages_v1_issue_authentication_token_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tokens_messages_v1_issue_authentication_token_request_proto_rawDesc), len(file_tokens_messages_v1_issue_authentication_token_request_proto_rawDesc)))
	})
	return file_tokens_messages_v1_issue_authentication_token_request_proto_rawDescData
}

var file_tokens_messages_v1_issue_authentication_token_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tokens_messages_v1_issue_authentication_token_request_proto_goTypes = []any{
	(*IssueAuthenticationTokenRequest)(nil), // 0: tokens.messages.v1.IssueAuthenticationTokenRequest
}
var file_tokens_messages_v1_issue_authentication_token_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tokens_messages_v1_issue_authentication_token_request_proto_init() }
func file_tokens_messages_v1_issue_authentication_token_request_proto_init() {
	if File_tokens_messages_v1_issue_authentication_token_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tokens_messages_v1_issue_authentication_token_request_proto_rawDesc), len(file_tokens_messages_v1_issue_authentication_token_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tokens_messages_v1_issue_authentication_token_request_proto_goTypes,
		DependencyIndexes: file_tokens_messages_v1_issue_authentication_token_request_proto_depIdxs,
		MessageInfos:      file_tokens_messages_v1_issue_authentication_token_request_proto_msgTypes,
	}.Build()
	File_tokens_messages_v1_issue_authentication_token_request_proto = out.File
	file_tokens_messages_v1_issue_authentication_token_request_proto_goTypes = nil
	file_tokens_messages_v1_issue_authentication_token_request_proto_depIdxs = nil
}
