// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: tokens/messages/v1/refresh_authentication_token_response.proto

package messagesv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RefreshAuthenticationTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshAuthenticationTokenResponse) Reset() {
	*x = RefreshAuthenticationTokenResponse{}
	mi := &file_tokens_messages_v1_refresh_authentication_token_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshAuthenticationTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshAuthenticationTokenResponse) ProtoMessage() {}

func (x *RefreshAuthenticationTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tokens_messages_v1_refresh_authentication_token_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshAuthenticationTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshAuthenticationTokenResponse) Descriptor() ([]byte, []int) {
	return file_tokens_messages_v1_refresh_authentication_token_response_proto_rawDescGZIP(), []int{0}
}

func (x *RefreshAuthenticationTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_tokens_messages_v1_refresh_authentication_token_response_proto protoreflect.FileDescriptor

const file_tokens_messages_v1_refresh_authentication_token_response_proto_rawDesc = "" +
	"\n" +
	">tokens/messages/v1/refresh_authentication_token_response.proto\x12\x12tokens.messages.v1\x1a\x1bbuf/validate/validate.proto\"B\n" +
	"\"RefreshAuthenticationTokenResponse\x12\x1c\n" +
	"\x05token\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x05tokenB\xfa\x01\n" +
	"\x16com.tokens.messages.v1B'RefreshAuthenticationTokenResponseProtoP\x01ZMgithub.com/FreibergVlad/url-shortener/proto/pkg/tokens/messages/v1;messagesv1\xa2\x02\x03TMX\xaa\x02\x12Tokens.Messages.V1\xca\x02\x12Tokens\\Messages\\V1\xe2\x02\x1eTokens\\Messages\\V1\\GPBMetadata\xea\x02\x14Tokens::Messages::V1b\x06proto3"

var (
	file_tokens_messages_v1_refresh_authentication_token_response_proto_rawDescOnce sync.Once
	file_tokens_messages_v1_refresh_authentication_token_response_proto_rawDescData []byte
)

func file_tokens_messages_v1_refresh_authentication_token_response_proto_rawDescGZIP() []byte {
	file_tokens_messages_v1_refresh_authentication_token_response_proto_rawDescOnce.Do(func() {
		file_tokens_messages_v1_refresh_authentication_token_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tokens_messages_v1_refresh_authentication_token_response_proto_rawDesc), len(file_tokens_messages_v1_refresh_authentication_token_response_proto_rawDesc)))
	})
	return file_tokens_messages_v1_refresh_authentication_token_response_proto_rawDescData
}

var file_tokens_messages_v1_refresh_authentication_token_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tokens_messages_v1_refresh_authentication_token_response_proto_goTypes = []any{
	(*RefreshAuthenticationTokenResponse)(nil), // 0: tokens.messages.v1.RefreshAuthenticationTokenResponse
}
var file_tokens_messages_v1_refresh_authentication_token_response_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tokens_messages_v1_refresh_authentication_token_response_proto_init() }
func file_tokens_messages_v1_refresh_authentication_token_response_proto_init() {
	if File_tokens_messages_v1_refresh_authentication_token_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tokens_messages_v1_refresh_authentication_token_response_proto_rawDesc), len(file_tokens_messages_v1_refresh_authentication_token_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tokens_messages_v1_refresh_authentication_token_response_proto_goTypes,
		DependencyIndexes: file_tokens_messages_v1_refresh_authentication_token_response_proto_depIdxs,
		MessageInfos:      file_tokens_messages_v1_refresh_authentication_token_response_proto_msgTypes,
	}.Build()
	File_tokens_messages_v1_refresh_authentication_token_response_proto = out.File
	file_tokens_messages_v1_refresh_authentication_token_response_proto_goTypes = nil
	file_tokens_messages_v1_refresh_authentication_token_response_proto_depIdxs = nil
}
